#!/bin/sh

# if app not exist
if [ ! -f /bin/transmission-daemon ]; then
    exit 0
fi

# wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

LOG="logger -t transmission"

start() {
    get_param
    if [ "$TransmissionEnabled" = "1" ] && [ -d $TRANSMISSION_HOME ] && [ ! "`pidof transmission-daemon`" ]; then
	$LOG "Start transmission daemon."
	/bin/transmission-daemon
    fi
}

stop() {
    if [ "`pidof transmission-daemon`" ]; then
	$LOG "Stop transmission daemon."
	killall -q transmission-daemon
	#wait before save files and connections stop
	sleep 5
	#kill if not stopped
	killall -q -SIGKILL transmission-daemon
    fi
}

get_param() {
    TransmissionEnabled=`nvram_get 2860 TransmissionEnabled`
    #include profile variables
    . /etc/profile
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

	reload)
            killall -HUP transmission-daemon
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|reload}"
            exit 1
esac
