#!/bin/sh

# if app not exist
if [ ! -f /bin/transmission-daemon ] || [ ! -d /proc/bus/usb ]; then
    exit 0
fi

# wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#include global config
. /etc/scripts/global.sh

LOG="logger -t transmission"

start() {
    get_param
    if [ "$TransmissionEnabled" = "1" ] && [ ! "`pidof transmission-daemon`" ]; then
      ( # fork to background
	# 10*10=100 seconds check media mount and exit
	count=0
	while [ "$public" = "" ]; do
	    count="$(($count+1))"
	    if [ "$count" != "10" ]; then
		$LOG "Disc not mounted... Please check USB connection. Wait 10sec and recheck. $count"
	        sleep 10
		# recheck public set
		. /etc/profile
	    else
		exit 0
	    fi
	done
	$LOG "Start transmission daemon."
	mkdir -p $TRANSMISSION_HOME
	if [ "$TransAuthor" = "1" ]; then
		authory="-t -u $TransLogin -v $TransPass"
	else
		authory="-T"
	fi
	nice -15 /bin/transmission-daemon -p $TransRPCPort -P $TransInPort $authory -x /var/run/transmission-daemon.pid
      ) & # fork to background
    fi
}

stop() {
    pid=`pidof transmission-daemon`
    if [ "$pid" != "" ]; then
	$LOG "Stop transmission daemon."
	killall -q transmission-daemon
	#wait before save files and connections stop
	sleep 2
	#kill if not stopped
	killall -q -SIGKILL transmission-daemon
    fi
}

get_param() {
    eval `nvram_buf_get 2860 TransmissionEnabled TransRPCPort TransAuthor TransInPort TransLogin TransPass`
    #include profile variables
    . /etc/profile
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

	reload)
            killall -HUP transmission-daemon
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|reload}"
            exit 1
esac
