#!/bin/sh

# if app not exist
if [ ! -f /bin/transmission-daemon ]; then
    exit 0
fi

# wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#include global config
. /etc/scripts/global.sh

LOG="logger -t transmission"

start() {
    get_param
    if [ "$public" = "" ];then
	$LOG "Disc not mounted... Please check USB connection."
	exit 0
    fi
    if [ "$TransmissionEnabled" = "1" ] && [ ! "`pidof transmission-daemon`" ]; then
	$LOG "Start transmission daemon."
	mkdir -p $TRANSMISSION_HOME
	if [ "$TransAuthor" = "1" ]; then
		authory="-t -u $TransLogin -v $TransPass"
	else
		authory="-T"
	fi
		nice -15 /bin/transmission-daemon -p $TransRPCPort -P $TransInPort $authory -x /var/run/transmission-daemon.pid
    fi
}

stop() {
    if [ "`pidof transmission-daemon`" ]; then
	$LOG "Stop transmission daemon."
	killall -q transmission-daemon
	#wait before save files and connections stop
	sleep 5
	#kill if not stopped
	killall -q -SIGKILL transmission-daemon
    fi
}

get_param() {
    eval `nvram_buf_get 2860 TransmissionEnabled TransRPCPort TransAuthor TransInPort TransLogin TransPass`
    #include profile variables
    . /etc/profile
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

	reload)
            killall -HUP transmission-daemon
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|reload}"
            exit 1
esac
