#!/bin/sh

echo "Clean temporary files..."
find $PWD -name 'config.log' | xargs rm -f
find $PWD/user -name '*.o' | xargs rm -f
find $PWD -name '*.old' | xargs rm -f
find $PWD -name '*.log' | xargs rm -f
find $PWD -name CVS -type d | xargs rm -rf

rm -f .tmp*
rm -f sdk_version.h
rm -f version

make clean -C Uboot
make clean -C tools
make clean
make mrproper
