#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

echo "-------------CLEAN-ALL---------------"
rm -rf $ROOTDIR/images
if [ "$1" != "RELEASE" ]; then
    rm -rf $ROOTDIR/releases
fi
make clean
echo "--------------MRPROPER---------------"
make mrproper
mkdir -p $ROOTDIR/releases
mkdir -p $ROOTDIR/images
rm -f linux
