#!/bin/sh

PWD=`pwd`

MODE=acorp

rm -rf $PWD/releases
mkdir -p $PWD/releases

./clear
nice -19 ./compile 2T2R $MODE
cp -f $PWD/images/*.zip $PWD/releases

./clear
nice -19 ./compile 1T1R-32 $MODE
cp -f $PWD/images/*.zip $PWD/releases

./clear
nice -19 ./compile 1T1R $MODE
cp -f $PWD/images/*.zip $PWD/releases
