#!/bin/sh

PWD=`pwd`

rm -rf $PWD/releases
mkdir -p $PWD/releases

#DEVLIST="RT3052-2T2R-USB RT3052-2T2R RT3050-1T1R"

# i`m not have sample with this chips - not release build
#DEVLISTUNUSED="RT3350-1T1R RT3352-2T2R-USB RT3662-2T2R-5G-USB"

DEVLIST="DSL-N12U"

./clear

for devname in $DEVLIST
do
    ./clear RELEASE
    nice -19 ./compile "$devname"
    cp -f $PWD/images/*.zip $PWD/releases
done
