#!/bin/sh

DOS2UNIX=NO
FULLREBUILD=NO
VERSIONPKG="1.0.18.RU.`date +%d%m%Y`"

#---Set_env_ROOTDIR_to_current_dir---#
ROOTDIR=`pwd`                                                                                                                               
export ROOTDIR=$ROOTDIR 

#----WR-NL-4M-16M---WR-NL+-4M-32M----#
if [ "$1" = "" ]; then
    MODE=2T2R
    #MODE=1T1R
    #MODE=1T1R-32
else
    MODE=$1
fi

#----acorp--dlink--------------------#
if [ "$2" = "" ]; then
    VENDOR=acorp
    #VENDOR=dlink
else
    VENDOR=$2
fi

#------------------------------------#
#WR-N for full and WR-NL for ligth HW
if [ "$MODE" = "2T2R" ]; then
    DEVNAME=WR-N
else
    DEVNAME=WR-NL
fi
echo "" > sdk_version.h
echo "#define RT288X_SDK_VERSION \"$DEVNAME-$VERSIONPKG\"" >> sdk_version.h
echo "" >> sdk_version.h
echo "" > version
echo "RT288X_SDK_VERSION = \"$VERSIONPKG\"" >> version
echo "" >> version

#memoryzzz
#find . -type d | grep -v "git"

#for clear all binary
if [ "$FULLREBUILD" = "YES" ] ; then
echo -------------------------------FULL-CLEAR-------------------------------
    ./clear
fi

rm -rfv romfs/*
rm -rfv images/*

echo -------------------------------MAKE-TOOLS-------------------------------

make all -C tools

echo --------------------------------COPY-CONFIG-----------------------------
if [ "$MODE" = "1T1R" ] ; then
    cp -fv ./config-$VENDOR/config-kernel-1t1r	./linux/.config
    cp -fv ./config-$VENDOR/config-config-1t1r	./config/.config
    cp -fv ./config-$VENDOR/config-lib-1t1r	./lib/.config
fi
if [ "$MODE" = "1T1R-32" ] ; then
    cp -fv ./config-$VENDOR/config-kernel-1t1r-32	./linux/.config
    cp -fv ./config-$VENDOR/config-config-1t1r	./config/.config
    cp -fv ./config-$VENDOR/config-lib-1t1r	./lib/.config
fi
if [ "$MODE" = "2T2R" ] ; then
    cp -fv ./config-$VENDOR/config-config-2t2r	./config/.config
    cp -fv ./config-$VENDOR/config-kernel-2t2r	./linux/.config
    cp -fv ./config-$VENDOR/config-lib-2t2r	./lib/.config
fi
cp -fv ./config-$VENDOR/config-busybox	./user/busybox/.config
cp -fv ./config-$VENDOR/config-cpp	./uClibc++/.config
cp -fv ./config-$VENDOR/config-all	.config
ln -fs vendors/Ralink/RT3052/config.arch config.arch
ln -fs config/autoconf.h autoconf.h

echo -------------------------------MAKE-OLDCONFIGS---------------------------

make oldconfig
make dep

#for wantusoid`s like.
if [ "$DOS2UNIX" = "YES" ] ; then
echo ---------------------------------DOS2UNIX--------------------------------
    find -type f -exec dos2unix -U -b {} \;
fi

echo ---------------------------------MAKE-ALL--------------------------------
make

echo -----------------------------------PACK----------------------------------
mv -f images/*.bin "images/$VENDOR.$MODE.$VERSIONPKG.bin"
zip -r images/$VENDOR.$MODE.$VERSIONPKG.bin.zip images/*.bin
