#!/bin/sh

#include kernel config
. /bin/config.sh

PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
LOG="logger -t pppd"

lan_ip=`nvram_get 2860 lan_ipaddr`                                                                                       
nm=`nvram_get 2860 lan_netmask`     
Lan2Enabled=`nvram_get 2860 Lan2Enabled`                                                                                 
lan2_ipaddr=`nvram_get 2860 lan2_ipaddr`                                                                                 
lan2_netmask=`nvram_get 2860 lan2_netmask` 
    
    $LOG "Restore netfilter rules from pppd"
    iptables -D FORWARD -o $PPP_IFACE -j ACCEPT > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan_ip/$nm -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan2_ipaddr/$lan2_netmask -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D PREROUTING -i $PPP_IFACE -j MINIUPNPD > /dev/null 2>&1
    iptables -t filter -D FORWARD -i $PPP_IFACE -o ! $PPP_IFACE -j MINIUPNPD > /dev/null 2>&1

    $LOG "Restore DNS from pppd"                                                                                             
    cp -f /etc/resolv.conf /var/tmp/resolv.conf.tmp.$PPP_IFACE               

    if [ -f /etc/routes_ppp_replace ]; then
	$LOG "Delete user routes"
	/etc/routes_ppp_replace $PPP_IFACE del > /dev/null 2>&1
    fi

    if [ -f /tmp/ip-down-route-reload ]; then
	$LOG "Load old dgw from file"
	/tmp/ip-down-route-reload
	rm -f /tmp/ip-down-route-reload
    fi

    $LOG "Flush route cache"
    ip route flush cache

    if [ "$CONFIG_USER_CLEAN_NAT" != "" ]; then
	$LOG "Cleanup conntrack table"
	echo 0 > /proc/cleannat
    fi

    $LOG "Restart need service and rebuild shaper and iptables rules"
    services_restart.sh pppd
    service shaper restart

#run scrips from /etc/ppp/ip-down.d/
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
if [ -d /etc/ppp/ip-down.d/ -a -x /bin/run-parts ]; then
    /bin/run-parts /etc/ppp/ip-down.d/
fi
$LOG "Down is OK"
