#!/bin/sh

#include global config
. /etc/scripts/global.sh

PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
LOG="logger -t pppd"

lan_ip=`nvram_get 2860 lan_ipaddr`
lan_nm=`nvram_get 2860 lan_netmask`
Lan2Enabled=`nvram_get 2860 Lan2Enabled`
lan2_ipaddr=`nvram_get 2860 lan2_ipaddr`
lan2_netmask=`nvram_get 2860 lan2_netmask`
vpnPeerDNS=`nvram_get 2860 vpnPeerDNS`
chilli_net=`nvram_get 2860 chilli_net`

    $LOG "Disable forwarding for $PPP_IFACE interface"
    echo 0 > "/proc/sys/net/ipv4/conf/$PPP_IFACE/forwarding"

    $LOG "Restore netfilter rules from pppd"
    iptables -D FORWARD -o $PPP_IFACE -j ACCEPT > /dev/null 2>&1
    iptables -t filter -D FORWARD -i $PPP_IFACE -o ! $PPP_IFACE -j MINIUPNPD > /dev/null 2>&1

    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan_ip/$lan_nm -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $chilli_net -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan2_ipaddr/$lan2_netmask -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D PREROUTING -i $PPP_IFACE -j MINIUPNPD > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan_ip/$lan_nm -j SNAT --to-source $PPP_LOCAL > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $chilli_net -j SNAT --to-source $PPP_LOCAL > /dev/null 2>&1
    iptables -t nat -A POSTROUTING -o $PPP_IFACE -s $lan2_ipaddr/$lan2_netmask -j SNAT --to-source $PPP_LOCAL > /dev/null 2>&1

    #replace dns to default
    if [ "$vpnPeerDNS" != "off" ] && [ -f /etc/ppp/resolv.conf ] && [ -f /var/tmp/resolv.conf.tmp.$PPP_IFACE ]; then
	$LOG "Restore DNS from pppd"
	cp -f /var/tmp/resolv.conf.tmp.$PPP_IFACE /etc/resolv.conf
	# read for all write by root
	chmod 644 /etc/resolv.conf > /dev/null 2>&1
	rm -f /etc/ppp/resolv.conf > /dev/null 2>&1
	rm -f /var/tmp/resolv.conf.tmp.$PPP_IFACE > /dev/null 2>&1
	rm -f /var/tmp/resolv.$PPP_IFACE > /dev/null 2>&1
    fi

    #remove portforward rules
    if [ -f /etc/portforward_vpn ]; then
	/etc/portforward_vpn "D" "$PPP_IFACE" "$PPP_LOCAL" > /dev/null 2>&1
    fi

    #remove route rules
    if [ -f /etc/routes_ppp_replace ]; then
	$LOG "Delete user routes"
	/etc/routes_ppp_replace del $PPP_IFACE > /dev/null 2>&1
    fi

    $LOG "Restore default gateway"
    #clear all default route
    if [ -f /tmp/ip-down-route-reload ] || [ -f /tmp/default.gw ]; then
	while ip route del default ; do
    	    :
	done 
    fi

    #restore default gateway
    if [ -f /tmp/default.gw ]; then
	#resote old dgw
	olddgw=`tail -qn1 /tmp/default.gw`
	if [ "$olddgw" != "" ]; then
	    ip route replace default via $olddgw
	fi
    else
	if [ -f /tmp/ip-down-route-reload ]; then
	    /tmp/ip-down-route-reload
	    rm -f /tmp/ip-down-route-reload
	fi
    fi

    $LOG "Flush route cache"
    ip route flush cache

    $LOG "Restart need service and rebuild shaper and iptables rules"
    services_restart.sh pppd
    service shaper restart

#run scrips from /etc/ppp/ip-down.d/
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
if [ -d /etc/ppp/ip-down.d/ -a -x /bin/run-parts ]; then
    /bin/run-parts /etc/ppp/ip-down.d/
fi
$LOG "Down is OK"
