#!/bin/sh

LOG="logger -t pppd"

    $LOG "Replace DNS from pppd"
    cp -f /etc/resolv.conf /var/tmp/resolv.conf.tmp.$1
    grep -v -f /etc/resolv.conf /etc/ppp/resolv.conf > /var/tmp/resolv.$1
    cat /var/tmp/resolv.$1 >> /etc/resolv.conf

    $LOG "corbiba hack"
    ip route del $5
    
    $LOG "Calculate min mtu"
    MINMTU=`ip link show up | grep mtu | awk {' print $5-28 '} | sort -n -r | tail -n1`

    $LOG "Renew mss rules"
    iptables -t mangle -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
    iptables -t mangle -I FORWARD -p tcp -o ppp+ --tcp-flags SYN,RST SYN \
                            -m tcpmss --mss $MINMTU:1506 -j TCPMSS --set-mss $MINMTU
    iptables -t mangle -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
    echo $MINMTU > /tmp/ppp-mtu

    $LOG "Restart dns server, dyndns, ntp sync and rebuild shaper rules"
    service ntp stop
    service upnp stop
    service dnsserver stop
    service shaper stop
    service ddns stop
    service iptables stop

    service iptables start
    service ntp start
    service ddns start
    service dnsserver start
    service shaper start
    service upnp start

    $LOG "All is start OK"

export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
