#!/bin/sh

    #replace DNS from ppp
    cp -f /etc/resolv.conf /var/tmp/resolv.conf.tmp.$1
    grep -v -f /etc/resolv.conf /etc/ppp/resolv.conf > /var/tmp/resolv.$1
    cat /var/tmp/resolv.$1 >> /etc/resolv.conf

    #corbiba hack
    ip route del $5
    
    #calculate min mtu
    MINMTU=`ip link show | grep mtu | awk {' print $5-28 '} | sort -n -r | tail -n1`
    iptables -t mangle -A FORWARD -p tcp -o ppp+ --tcp-flags SYN,RST SYN \
                            -m tcpmss --mss $MINMTU:1506 -j TCPMSS --set-mss $MINMTU
    echo $MINMTU > /tmp/ppp-mtu

    #restart dns server and ntp sync
    service ntp stop
    service dnsserver stop
    service ntp start
    service dnsserver start

export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
