#!/bin/sh

start() {
 echo "Preconfigure..."
    export PATH=.:$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/etc/scripts

    echo "Delete old config"
    rm -f /etc/zebra.conf
    rm -f /etc/ripd.conf

    echo "Mount all filesystems"
    mount -a
    mount -t devpts /dev/pts /dev/pts
    mknod /dev/ptmx c 5 2
    
    echo "Create some folders"
    mkdir -p /var/run
    mkdir -p /var/lock
    mkdir -p /var/lock/subsys
    mkdir -p /var/log
    mkdir -p /var/tmp
    mkdir -p /var/run/xl2tpd

    mkdir /dev/pty
    mknod /dev/pty/m0             c       2       0
    mknod /dev/pty/m1             c       2       1
    mknod /dev/pty/m2             c       2       2
    mknod /dev/pty/m3             c       2       3
    mknod /dev/pty/m4             c       2       4
    mknod /dev/pty/m5             c       2       5
    mknod /dev/pty/m6             c       2       6
    mknod /dev/pty/m7             c       2       7
    mknod /dev/pty/m8             c       2       8
    mknod /dev/pty/m9             c       2       9
    mknod /dev/pty/m10    c       2       10
    mknod /dev/pty/m11    c       2       11
    mknod /dev/pty/m12    c       2       12
    mknod /dev/pty/m13    c       2       13
    mknod /dev/pty/m14    c       2       14
    mknod /dev/pty/m15    c       2       15

    mkdir /dev/tts
    mknod /dev/tts/0              c       4       64
    mknod /dev/tts/1              c       4       65

    mkdir /dev/cua
    mknod /dev/cua/0              c       5       64

    mkdir /dev/misc
    mknod /dev/misc/rtc   c       10      135

    #modify permissions
    chmod 777 /tmp

    echo "Start nvram daemon"
    nvram_daemon &
    
#if compile date fille is exist
if [ -f /etc/compile-date ]; then
    echo "Restore time to build time or save time"
    BUILDDATE=`cat /etc/compile-date`
    if [ $BUILDDATE != "" ]; then
	date -s $BUILDDATE
    fi
fi

echo "Reinit power mode for all switch ports" #workaroud for dir
    #disable
    config-vlan.sh 2 DDDDD
    #full 100mbit
    config-vlan.sh 2 EEEEE
    #full 10mbit
    #config-vlan.sh 2 HHHHH
    #reset all phy and auto negotinate now
    config-vlan.sh 2 RRRRR
}

stop() {
 echo "Stop preconfigure."
 killall -q nvram_daemon
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
