#!/bin/sh

#only clean load start this
if [ -f /var/run/goahead.pid ]; then
    exit 0
fi

LOG="echo PRECONFIG"

start() {
 $LOG "Preconfigure..."
    export PATH=.:$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/etc/scripts

    $LOG "Mount all filesystems"
    mount -t devpts /dev/pts /dev/pts
    mount -a

    $LOG "Delete old config"
    rm_conf="zebra.conf ripd.conf macipfilter websfilter portforward ppp_firewall resolv_conf.bak"
    for file in $rm_conf ; do
	rm -f /etc/$file
    done
    
    $LOG "Create some folders"
    ndirs="/var/run /var/lock /var/lock/subsys /var/log /var/tmp /var/run/xl2tpd /etc/ppp/ip-up.d /etc/ppp/ip-down.d"
    for dir in $ndirs ; do
        mkdir -p "$dir" 2> /dev/null
    done

    $LOG "Create need device node"
    mknod /dev/ptmx c 5 2

    mkdir -p /dev/pty
    for i in `seq 0 15`; do
	mknod /dev/pty/m$i c 2 $i
    done

    mkdir -p /dev/tts
    mknod /dev/tts/0              c       4       64
    mknod /dev/tts/1              c       4       65

    mkdir -p /dev/cua
    mknod /dev/cua/0              c       5       64

    mkdir -p /dev/misc
    mknod /dev/misc/rtc   c       10      135

    #modify permissions
    chmod 777 /tmp

    #ralink depended
    mknod /dev/hwnat0 c 220 0
    mknod /dev/swnat0 c 210 0

    mknod /dev/i2cM0 c 218 0
    mknod /dev/I2S c 234 0
    mknod /dev/ac0 c 240 0
    mknod /dev/acl0 c 230 0
    mknod /dev/aci0 c 254 0
    mknod /dev/aci1 c 254 1
    mknod /dev/aci2 c 254 2
    mknod /dev/aci3 c 254 3
    mknod /dev/gpio c 252 0
    mknod /dev/gpio0 c 252 0
    mknod /dev/gpio1 c 252 1

    mknod /dev/rdm0 c 254 0
    mknod /dev/PCM c 233 0

#if compile date fille is exist
if [ -f /etc/compile-date ]; then
    $LOG "Restore time to build time or save time"
    BUILDDATE=`cat /etc/compile-date`
    if [ "$BUILDDATE" != "" ]; then
	date -s $BUILDDATE
    fi
fi

if [ `cat /proc/meminfo | awk '/MemTotal:/ {print ($2>16384)}'` -eq 1 ]; then
    $LOG "Copy web pages to tmpfs"
    mkdir -p /tmp/web
    cp -rpf /web/* /tmp/web
else
    $LOG "16M device detected, creating symlink for web pages in tmpfs"
    ln -s /web /tmp/web
fi

}

stop() {
 echo "" > /dev/null
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
