#!/bin/sh

#only clean load start this
if [ -f /var/run/goahead.pid ]; then
    exit 0
fi

LOG="echo PRECONFIG"

start() {
 $LOG "Preconfigure..."

    #create fstab if not exist
    touch /etc/fstab

    mount -t devpts /dev/pts /dev/pts
    mount -a
    chmod 777 /tmp

    $LOG "Delete old configs."
    rm_conf="zebra.conf ripd.conf macipfilter websfilter portforward ppp_firewall routes_ppp_replace resolv_conf.bak ppp/resolv.conf"
    for file in $rm_conf ; do
	rm -f /etc/$file
    done

    $LOG "Create some folders in var and etc."
    ndirs="/var/run /var/lock /var/lock/subsys /var/log /var/tmp /var/run/xl2tpd /etc/ppp/ip-up.d /etc/ppp/ip-down.d"
    for dir in $ndirs ; do
	mkdir -p "$dir" > /dev/null 2>&1
    done

    if [ -f /tmp/is_32ram_dev ]; then
	$LOG "Copy web pages to tmpfs."
        mkdir -p /tmp/web
        cp -rpf /web/* /tmp/web
    else
	$LOG "16M device detected, creating symlink for web pages in tmpfs."
        ln -sf /web /tmp/web
    fi

    #this may be need for some apps
    ln -sf /var/lock /var/locks
}

stop() {
 echo "" > /dev/null
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
