#!/bin/sh


LOG="echo HOTPLUG: "

start() {
if [ -f /bin/mdev ]; then
    #create device in /dev
    mdev -s
    if [ -f /proc/sys/kernel/hotplug ]; then
	$LOG "Start mdev for support HOTPLUG"
	printf "
		# <device regex> <uid>:<gid> <octal permissions> [<@|$|*> <command>]
		# The special characters have the meaning:
		# @ Run after creating the device.
		# $ Run before removing the device.
		# * Run both after creating and before removing the device.\n" > /etc/mdev.conf
	#include kernel config
	. /etc/scripts/config.sh
	if [ "$CONFIG_USB_STORAGE" != "" ]; then
		mount -t tmpfs tmpfs /media
		# Check & load ext2 here or in automount.sh (else only ntfs-3g works) ?
		modprobe -q ext2
		echo "sd[a-z][1-9] 0:0 0660 */sbin/automount.sh \$MDEV" >> /etc/mdev.conf
	fi
	echo "/sbin/mdev" > /proc/sys/kernel/hotplug
    fi
fi
}

stop() {
 $LOG "Stop mdev generate..."
    killall -q mdev
    killall -q -9 mdev
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
