#!/bin/sh

# if app not exist
if [ ! -f /bin/mdev ] || [ ! -f /proc/sys/kernel/hotplug ]; then
    exit 0
fi

LOG="echo HOTPLUG"

start() {
    $LOG "Start mdev for support HOTPLUG"
    printf "
	# <device regex> <uid>:<gid> <octal permissions> [<@|$|*> <command>]
	# The special characters have the meaning:
	# @ Run after creating the device.
	# $ Run before removing the device.
	# * Run both after creating and before removing the device.\n" > /etc/mdev.conf
    if [ -d /proc/bus/usb ]; then
	echo "sd[a-z][1-9] 0:0 0660	*/etc/scripts/automount.sh \$MDEV" >> /etc/mdev.conf
	#echo "sg[0-9] 0:0 0660		*/etc/scripts/modem-switch.sh $MDEV" >> /etc/mdev.conf
	#echo "sr[0-9] 0:0 0660		*/etc/scripts/modem-switch.sh $MDEV" >> /etc/mdev.conf
	#echo "ttyUSB[0-9] 0:0 0660	*/etc/scripts/modem-call.sh $MDEV" >> /etc/mdev.conf
	#echo "ttyACM[0-9] 0:0 0660	*/etc/scripts/modem-call.sh $MDEV" >> /etc/mdev.conf
	#echo "lp[0-9] 0:0 0660		*/etc/scripts/p910.sh $MDEV" >> /etc/mdev.conf
    fi

    #set mdev as kernel hotplug helper
    echo "/sbin/mdev" > /proc/sys/kernel/hotplug

    if [ -d /proc/bus/usb ]; then
	#enable drivers autoprobe for all usb devices
	if [ -f /sys/subsystem/usb/drivers_autoprobe ]; then
	    echo 1 > /sys/subsystem/usb/drivers_autoprobe
	fi

	#touch uevent for cold start usb and other hotplug devices allready connected to SOC at boot
	find /sys -type f -name 'uevent' | while read dev_event; do
    	    echo 1 > $dev_event
	done
    fi
}


stop() {
 $LOG "Stop mdev generate..."
    killall -q mdev
    killall -q -9 mdev
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
