#!/bin/sh

start() {
 echo "Start klogd"
    klogd &

 echo "Start syslogd"
    syslogd -D &
}

stop() {
 echo "Stop goahead"
    killall -9 klogd
    killall -9 syslogd
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
