#!/bin/sh

start() {
 echo "Start klogd"
    klogd &

 echo "Start syslogd"
    #log to /var/log/messages
    syslogd -b0 -s20 -l6 -S -D &
    #log to memory buffer
    syslogd -C10 -b0 -s20 -l6 -S -D &
}

stop() {
 echo "Stop syslog and klog"
    killall -q -9 klogd
    killall -q -9 syslogd
    rm -f /var/log/messages > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
