#!/bin/sh

start() {
 echo "Start klogd"
    klogd &

 echo "Start syslogd"
    syslogd -D &
}

stop() {
 echo "Stop syslog and klog"
    killall -q -9 klogd > /dev/null 2>&1
    killall -q -9 syslogd > /dev/null 2>&1
    rm -f /var/log/messages > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
