#!/bin/sh

modtest=`uname -r`
moddir=/lib/modules/$modtest
MODULES=`find /lib/modules -type f`;
FULLMODULELOAD="NO"
CONNTRACKMODULELOAD="YES"

start() {
 echo "Starting modules.dep generate..."
    #depmod
    ln -sf $moddir/modules.dep /etc/modules.dep
 ############LOAD##ALL###MODULES###################
 if [ $FULLMODULELOAD = "YES" ]; then
    for i in $MODULES; do
	echo $i;
	insmod $i > /dev/null 2>&1
    done
 else
  ############CONNTRCAK###FILTERS##################
  if [ $CONNTRACKMODULELOAD = "YES" ]; then
    MODULES_IPT=$MODULES/kernel/net/ipv4/netfilter
    for i in $MODULES_IPT; do
	echo $i;
	insmod $i > /dev/null 2>&1
    done
  fi
  ##################################################
 fi
}

stop() {
 echo "Stop modules.dep generate..."
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
