#!/bin/sh

modtest=`uname -r`
moddir=/lib/modules/$modtest
MODULES=`find /lib/modules -type f`;
MODULES_IPT=$MODULES/kernel/net/ipv4/netfilter

start() {
 echo "Starting modules..."
    depmod -a -n >  /tmp/modules.dep
    ln -sf /tmp/modules.dep /etc/modules.dep
}

stop() {
 echo "Stop modules.dep generate..."
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
