#!/bin/sh

#include functions from script
. /etc/scripts/functions

start() {
    echo "Start loopback network interface..."
    ifconfig lo 127.0.0.1 up
    ip route add 127.0.0.0/8 dev lo
    ip route add 127.0.0.0/8 dev lo table default

    echo "Add bridge in the system"
    brctl addbr br0

    echo "Drop ip in eth2"
    ifconfig eth2 0.0.0.0

    echo "Set hostname"
    /bin/hostname Wive-RTNL
}

stop() {
    echo ""
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
