#!/bin/sh

start() {
 echo "Start mdev for support HOTPLUG"
    mdev -s
    echo "# <device regex> <uid>:<gid> <octal permissions> [<@|$|*> <command>]" > /etc/mdev.conf
    echo "# The special characters have the meaning:" >> /etc/mdev.conf
    echo "# @ Run after creating the device." >> /etc/mdev.conf
    echo "# $ Run before removing the device." >> /etc/mdev.conf
    echo "# * Run both after creating and before removing the device." >> /etc/mdev.conf
    echo "sd[a-z][1-9] 0:0 0660 */sbin/automount.sh \$MDEV" >> /etc/mdev.conf
    echo "/sbin/mdev" > /proc/sys/kernel/hotplug
}

stop() {
 echo "Stop mdev generate..."
    killall mdev > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
