#!/bin/sh

LOG="logger -t ntp"

start() {
    $LOG "Set timezone"

    tz=`nvram_get 2860 TZ`
    if [ "$tz" = "" ]; then
        tz="MSD"
    fi

    echo "$tz" > /etc/tmpTZ
    sed -e 's#.*_\(-*\)0*\(.*\)#GMT-\1\2#' /etc/tmpTZ > /etc/tmpTZ2
    sed -e 's#\(.*\)--\(.*\)#\1\2#' /etc/tmpTZ2 > /etc/TZ
    rm -rf /etc/tmpTZ
    rm -rf /etc/tmpTZ2

    if [ -f /etc/compile-date ] && [ ! -f /tmp/time_restored ]; then
        $LOG "Restore time to build time or save time."
	BUILDDATE=`cat /etc/compile-date`
        if [ "$BUILDDATE" != "" ]; then
	    date -s "$BUILDDATE"
	    touch /tmp/time_restored
        fi
    fi

    # if app not exist
    if [ ! -f /bin/ntpd ]; then
	exit 0
    fi

    #wait to start web and run from goahead code
    . /etc/scripts/web_wait.sh
    web_wait

    NTPEnabled=`nvram_get 2860 NTPEnabled`
    srv=`nvram_get 2860 NTPServerIP`
    if [ "$NTPEnabled" = "on" ] && [ "$srv" != "" ]; then
	$LOG "Starting NTPD"
	ntpd -d -p "$srv" &
    fi
}

stop() {
 $LOG "Stopping NTPD"
    killall -q ntpd
    killall -q -9 ntpd
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
