#!/bin/sh

#include functions from script
. /etc/scripts/functions

start() {
    stop
#    echo "Start AP mode"
#    echo "Generate config and module load"
#    ralink_init gen 2860
#    ralink_init make_wireless_config rt2860
#    modprobe rt2860v2_ap
#    echo "Add ra0 in bridge"
#    brctl addif br0 ra0
#    ifconfig ra0 up
}

stop() {
echo "Stop RA interfaces"
    brctl delif br0 ra0
    ifRaxWdsxDown
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
