#!/bin/sh

start() {
 echo "Starting sysctl: "
    sysctl -w -p /etc/sysctl.conf > /dev/null 2>&1

  echo "Tune with proc"
    #more reserved memory for send/recive tcp buffers 192Kb max
    echo "64000 128000 192000" > /proc/sys/net/ipv4/tcp_mem
    echo "64000 128000 192000" > /proc/sys/net/ipv4/tcp_rmem
    echo "64000 128000 192000" > /proc/sys/net/ipv4/tcp_wmem
    #memory
    echo 192  > /proc/sys/vm/min_free_kbytes
    echo 128  > /proc/sys/kernel/threads-max
    echo 1    > /proc/sys/vm/page-cluster
    echo 0    > /proc/sys/vm/overcommit_ratio
    echo 0    > /proc/sys/vm/overcommit_memory
    #on kernel crash
    echo 1    > /proc/sys/kernel/panic
    echo 1    > /proc/sys/kernel/panic_on_oops
    echo 1    > /proc/sys/vm/panic_on_oom
}

stop() {
 echo "Stopping sysctl: "
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
