#!/bin/sh

start() {
 echo "Tune with sysctl: "
    sysctl -w -p /etc/sysctl.conf > /dev/null 2>&1

  echo "Tune network stack and memory usadge fo small memory devices"
    # tcp buff size
    MAX_MEM=`free | grep Total | awk '{ print ($4-1228)*1024 }'`
    CORE_MEM=`echo $MAX_MEM | awk '{ print ($1)/4 }' | cut -d '.' -f1`
    IPV4_MEM=`echo $MAX_MEM | awk '{ print ($1)/6 }' | cut -d '.' -f1`
    # set sysctl
    sysctl -w net.core.rmem_max=$MAX_MEM
    sysctl -w net.core.wmem_max=$MAX_MEM
    sysctl -w net.ipv4.tcp_rmem="4096 43689 $CORE_MEM"
    sysctl -w net.ipv4.tcp_wmem="4096 16384 $CORE_MEM"
    sysctl -w net.ipv4.tcp_mem="2048 2560 $IPV4_MEM"

  echo "Tune with proc"
    #memory
    echo 192  > /proc/sys/vm/min_free_kbytes
    echo 128  > /proc/sys/kernel/threads-max
    echo 1    > /proc/sys/vm/page-cluster
    echo 0    > /proc/sys/vm/overcommit_ratio
    echo 0    > /proc/sys/vm/overcommit_memory
    #on kernel crash
    echo 1    > /proc/sys/kernel/panic
    echo 1    > /proc/sys/kernel/panic_on_oops
    echo 1    > /proc/sys/vm/panic_on_oom
}

stop() {
 echo "Stopping sysctl: "
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
