#!/bin/sh

start() {
 echo "Start loopback network interface..."
    ifconfig lo 127.0.0.1 up
    ip route add 127.0.0.0/8 dev lo
    ip route add 127.0.0.0/8 dev lo table default

#  echo "Add bridge in the system"
#    brctl addbr br0
#    ifconfig br0 0.0.0.0 up 
}

stop() {
 ifconfig br0 down
 brctl delbr br0
 echo "OK"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
