#!/bin/sh

start() {
 echo "Start loopback network interface..."
    ifconfig lo 127.0.0.1 up
    ip route add 127.0.0.0/8 dev lo
    ip route add 127.0.0.0/8 dev lo table default
}

stop() {
 echo "Stop br0 network interface..."
 ifconfig br0 down > /dev/null 2>&1
 brctl delbr br0 > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
