#!/bin/sh

LOG="echo SYSLOG"

start() {
 $LOG "Start klogd"
    klogd &

 $LOG "Start syslogd"
    #log to /var/log/messages
    syslogd -b0 -s20 -l7 -S -D &
}

stop() {
 $LOG "Stop syslog and klog"
    killall -q klogd
    killall -q -9 klogd
    killall -q syslogd
    killall -q -9 syslogd
    rm -f /var/log/messages > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
