#!/bin/sh

LOG="echo SYSLOG"

start() {
    if [ "$KLogd" != "0" ] && [ "$KLogd" != "" ]; then
	$LOG "Start klogd"
	klogd &
    fi

    if [ "$SysLogd" != "0" ] && [ "$SysLogd" != "" ]; then
	if [ "$RemoteSysLogIP" = "0.0.0.0" ] && [ "$SysLogd" = "" ]; then
	    $LOG "Start syslogd local"
	    syslogd -b0 -s20 -l7 -S -D &
	else
	    $LOG "Start syslogd remote mode. Host $RemoteSysLogIP"
	    syslogd -b0 -s20 -l7 -R $RemoteSysLogIP -D &
	fi
    fi
}

stop() {
 $LOG "Stop syslog and klog"
    killall -q klogd
    killall -q -SIGKILL klogd
    killall -q syslogd
    killall -q -SIGKILL syslogd
    rm -f /var/log/messages > /dev/null 2>&1
}

get_param() {
    KLogd=`nvram_get 2860 KLogd`
    SysLogd=`nvram_get 2860 SysLogd`
    RemoteSysLogIP=`nvram_get 2860 RemoteSysLogIP`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
