#!/bin/sh

#get params
. /sbin/global.sh

start() {
 ip=`nvram_get 2860 lan_ipaddr`
 nm=`nvram_get 2860 lan_netmask`
 echo "Add bridge in the system"
    brctl addbr br0
    ifconfig $lan_if down
    if [ "$lan_if" != "" ]; then
	ifconfig $lan_if $ip netmask $nm
    else
	ifconfig $lan_if 0.0.0.0	
    fi
    #only prepare... config from goahead code

 echo "Add default gateway"
    opmode=`nvram_get 2860 OperationMode`
    if [ "$opmode" = "0" ]; then
        gw=`nvram_get 2860 wan_gateway`
        pd=`nvram_get 2860 wan_primary_dns`
        sd=`nvram_get 2860 wan_secondary_dns`
        route del default
        route add default gw $gw
        config-dns.sh $pd $sd
    fi
}

stop() {
 echo "Stop lan - NO NEEED!"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
