#!/bin/sh

#get params
. /sbin/global.sh

start() {
 ip=`nvram_get 2860 lan_ipaddr`
 nm=`nvram_get 2860 lan_netmask`
 ip_2=`nvram_get 2860 lan2_ipaddr`
 nm_2=`nvram_get 2860 lan2_netmask`
 gw=`nvram_get 2860 wan_gateway`
 opmode=`nvram_get 2860 OperationMode`
 lan2enabled=`nvram_get 2860 Lan2Enabled`

 ifconfig $lan_if down
 if [ "$lan_if" != "" ]; then
    ifconfig $lan_if $ip netmask $nm
 else
    ifconfig $lan_if 0.0.0.0	
 fi

 if [ "$lan2enabled" = "1" ]; then
 echo "Add LAN2 iface"
        if [ "$opmode" = "0" ] || [ "$opmode" = "1" ] || [ "$opmode" = "3" ]; then
                ifconfig "br0:9" "$ip_2" netmask "$nm_2"
                echo "ifconfig "br0:9" "$ip_2" netmask "$nm_2""
        elif [ "$opmode" = "2" ]; then
                ifconfig "eth2:9" "$ip_2" netmask "$nm_2"
                echo "ifconfig "eth2:9" "$ip_2" netmask "$nm_2""
        fi
 fi

 if [ "$opmode" = "0" ]; then
  route del default
    if [ "$gw" != "" ] && [ "$gw" != "0.0.0.0" ]; then
	echo "Add default gateway"
	route add default gw $gw
    fi 
 fi

}

stop() {
 echo "Stop lan!"
    ifconfig $lan_if down > /dev/null 2>&1
    ifconfig "br0:9" down > /dev/null 2>&1
    ifconfig "eth2:9" down > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
