#!/bin/sh

LOG="logger -t pass"

start() {
 $LOG "Set current password"
    #get user/password
    get_param    

    #generate pass file
    printf "$admID::0:0:Adminstrator:/:/bin/sh\nnobody:x:99:99:Nobody:/:\n" > /etc/passwd

    #generate group file
    printf "$admID:x:0:$admID\nnobody:x:99:\n" > /etc/group

    #set new password
    echo "$admID:$admPW" > /tmp/tmpchpw
    chpasswd < /tmp/tmpchpw
    rm -f /tmp/tmpchpw
}

stop() {
    echo "" > /dev/null
}

get_param() {
    admID=`nvram_get 2860 Login`
    admPW=`nvram_get 2860 Password`
}
case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
