#!/bin/sh

start() {
 echo "Set hostname"
    host=`nvram_get 2860 HostName`
    if [ "$host" = "" ]; then
        host="Wive-RTNL"
        nvram_set 2860 HostName $host
    fi
    /bin/hostname $host
}

stop() {
 echo "OK"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
