#!/bin/sh

#include functions from script
. /etc/scripts/functions

start() {
    echo "Start nvram daemon"
    nvram_daemon &
}

stop() {
echo ""
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
