#!/bin/sh

start() {
 echo "PASSWD gen"
    admID=`nvram_get 2860 Login`
    if [ "$admID" = "" ]; then
        admID="Admin"
        nvram_set 2860 Login Admin
    fi
        admPW=`nvram_get 2860 Password`
    if [ "$admPW" = "" ]; then
        admPW="Admin"
        nvram_set 2860 Password Admin
    fi
    
    login=`nvram_get 2860 Login`
    pass=`nvram_get 2860 Password`
    echo "$login::0:0:Adminstrator:/:/bin/sh" > /etc/passwd
    echo "nobody:x:99:99:Nobody:/:" >> /etc/passwd
    echo "$login:x:0:$login" > /etc/group
    echo "nobody:x:99:" >> /etc/group
    chpasswd.sh $login $pass
}

stop() {
 echo "OK"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
