#!/bin/sh

LOG="echo RESOLVE: "

start() {
get_param
if [ ! -f /var/run/goahead.pid ] || [ "$static" = "on" ] ; then
 $LOG "Generate resolve: "

    # backup file without nameserver part
    sed -e '/nameserver/d' $fname > $fbak

    # if nameservers is null add 127.0.0.1
    if  [ "$pd" = "" ] && [ "$sd" = "" ]; then
	echo "nameserver 127.0.0.1" > $fname
    else
	#drop current DNS
	echo > $fname
        #add new records
	if [ "$pd" != "" ]; then
	    echo "nameserver $pd" >> $fname
	fi
	if [ "$sd" != "" ]; then
	    echo "nameserver $sd" >> $fname
	fi
    fi

    cat $fbak >> $fname
    rm -f $fbak
fi
}

stop() {
 echo "" > /dev/null
}

get_param() {
    static=`nvram_get 2860 wan_static_dns`
    pd=`nvram_get 2860 wan_primary_dns`
    sd=`nvram_get 2860 wan_secondary_dns`
    fname="/etc/resolv.conf"
    fbak="/etc/resolv_conf.bak"

    #if no file create
    if [ -f $fname ]; then
        touch $fname
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
