#!/bin/sh

LOG="logger -t resolv"

start() {
get_param
if [ ! -f /var/run/goahead.pid ] || [ "$wan_static_dns" = "on" ]; then

    # backup file without nameserver part
    sed -e '/nameserver/d' $fname > $fbak

    # drop current
    rm -f $fname
    touch $fname
    # if nameservers is null add 127.0.0.1
    if [ "$pd" != "" ] || [ "$sd" != "" ]; then
	$LOG "Generate resolv DNS1: $pd DNS2: $sd"
	if [ "$pd" != "" ]; then
	    echo "nameserver $pd" >> $fname
	fi
	if [ "$sd" != "" ]; then
	    echo "nameserver $sd" >> $fname
	fi
    elif  [ "$pd" = "" ] && [ "$sd" = "" ] && [ "$dnsPEnabled" = "1" ]; then
	$LOG "Generate resolv at local."
	echo "nameserver 127.0.0.1" > $fname
    else
	$LOG "Not correct DNS use Google dns"
	echo "nameserver 8.8.8.8" >> $fname
	echo "nameserver 8.8.4.4" >> $fname
    fi

    cat $fbak >> $fname
    rm -f $fbak
    # read for all write by root
    chmod 644 "$fname" > /dev/null 2>&1
fi
}

stop() {
 echo "" > /dev/null
}

get_param() {
    wan_static_dns=`nvram_get 2860 wan_static_dns`
    pd=`nvram_get 2860 wan_primary_dns`
    sd=`nvram_get 2860 wan_secondary_dns`
    dnsPEnabled=`nvram_get 2860 dnsPEnabled`
    fname="/etc/resolv.conf"
    fbak="/etc/resolv_conf.bak"

    #if no file create
    if [ -f $fname ]; then
        touch $fname
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
