#!/bin/sh

start() {
    if [ -f /etc/dropbear/dropbear_dss_host_key ]; then
	echo "DSS file exist"
    else
	echo "Generate host key for first start"
        echo "If no DSS key  and generate new key"
        dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
	fs save
    fi

    if [ -f /etc/miniupnpd.conf.uuid ]; then
       echo "Use exist UUID file"
    else
       echo "Generate UUID for miniupnpd"
       num=0
        for i in `seq 1 36`; do
            id=`cat /dev/urandom | hexdump | head -1 | cut -c9`
            num=`expr $num + 1`
            if [ $num = "9" ] || [ $num = "19" ] || [ $num = "24" ]; then
	        id="-"
            fi
            outid=$outid$id
        done
        echo "UPNP UUID is $outid"
        echo "uuid=""$outid" >> /etc/miniupnpd.conf.uuid
        serial=`hostid`
        echo "serial=""$serial" >> /etc/miniupnpd.conf.uuid
        fs save
    fi
}

stop() {
 echo "OK"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
