#!/bin/sh

start() {
echo "Generate host key for first start"
    admID=`nvram_get 2860 Login`
    if [ -f /etc/dropbear/dropbear_dss_host_key ]; then
	echo DSS file exist
    else
        echo "Generating ssh keys"
        echo If no DSS key  and generate new key
        dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
    fi

echo "Starting inetd: "
    if [ "$admID" = "" ]; then
        admID="Admin"
	echo "ssh     stream  tcp     nowait  $admID    /bin/dropbear       /bin/dropbear -i" > /etc/inetd.conf
        echo "telnet  stream  tcp     nowait  $admID    /bin/telnetd        /bin/telnetd -i"  >> /etc/inetd.conf
    fi
    /sbin/inetd
}

stop() {
 echo "Stopping inetd: "
 killall inetd
 echo " Ok"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
