#!/bin/sh

#include kernel config
. /bin/config.sh

start() {
 echo "Start loopback interface..."
    ip link set lo up
    ip addr flush dev lo
if [ $CONFIG_IPV6 != "" ] ; then
    ip -6  addr flush dev lo
fi
    ip addr add 127.0.0.0/8 dev lo
if [ $CONFIG_IPV6 != "" ] ; then
    ip -6 addr add ::1/128 dev lo
fi
    ip route add 127.0.0.0/8 dev lo
    ip route add 127.0.0.0/8 dev lo table default
}

stop() {
 echo "Stop br0 and loopback interfaces..."
    ip link set lo down > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
