#!/bin/sh

#get params
. /sbin/global.sh

lan_ip=`nvram_get 2860 lan_ipaddr`
nm=`nvram_get 2860 lan_netmask`
NAT=`nvram_get 2860  natEnabled`

#calculate min mtu
MINMTU=`ip link show | grep mtu | awk {' print $5-28 '} | sort -n -r | tail -n1`

start() {
 echo "Starting IPTABLES: "
        iptables -A INPUT  -i lo+ -j ACCEPT
	iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -I INPUT -m state --state INVALID -j DROP

        iptables -N servicelimit
        iptables -A INPUT -j servicelimit
	
        iptables -F servicelimit
	#telnet ssh snmp limit
        iptables -A servicelimit -p tcp --dport 21:23 -m connlimit --connlimit-above 4 -j REJECT
	#web limit
        iptables -A servicelimit -p tcp --dport 80 -m connlimit --connlimit-above 8 -j REJECT
        #icmp limit
	iptables -A servicelimit -p icmp --icmp-type echo-request -m limit --limit 10/s -j RETURN
        iptables -A servicelimit -p icmp --icmp-type echo-request -j DROP

	#tune mss size for tranzit packets
	iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
	iptables -t mangle -A FORWARD -p tcp ! -o ppp+ --tcp-flags SYN,RST SYN \
			    -m tcpmss --mss $MINMTU:1506 -j TCPMSS --set-mss $MINMTU
        
	if [ "$NAT" = "1" ]; then
	echo "Add masqrade rules"
    	    iptables -t nat -A POSTROUTING -o eth+ -s $lan_ip/$nm -j MASQUERADE
	    iptables -t nat -A POSTROUTING -o ra+  -s $lan_ip/$nm -j MASQUERADE
	fi
}

stop() {
 echo "Stopping IPTABLES: "
	echo -e "*nat\nCOMMIT\n*filter\nCOMMIT\n*mangle\nCOMMIT\n" | iptables-restore > /dev/null 2>&1
	iptables -F > /dev/null 2>&1
	iptables -t nat -F > /dev/null 2>&1
        iptables -t filter -F > /dev/null 2>&1
        iptables -t mangle -F > /dev/null 2>&1
        iptables -X > /dev/null 2>&1
        iptables -t nat -X > /dev/null 2>&1
        iptables -t filter -X > /dev/null 2>&1
        iptables -t mangle -X > /dev/null 2>&1

        iptables -t mangle -F PREROUTING > /dev/null 2>&1
        iptables -t mangle -F FORWARD > /dev/null 2>&1
        iptables -t mangle -F INPUT > /dev/null 2>&1
        iptables -t mangle -F OUTPUT > /dev/null 2>&1
        iptables -t mangle -F POSTROUTING > /dev/null 2>&1

        iptables -t nat -Z > /dev/null 2>&1
        iptables -t filter -Z > /dev/null 2>&1
        iptables -t mangle -Z > /dev/null 2>&1
	iptables -Z > /dev/null 2>&1
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
