#!/bin/sh

LOG="echo CRON: "

start() {
 $LOG "Starting crontab: "
 /sbin/crond -l 0 -L /var/log/cron.log
}

stop() {
 $LOG "Stopping crontab: "
 killall -q crond
 killall -q -9 crond
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
