#!/bin/sh

start() {
echo "Starting inetd: "
    admID=`nvram_get 2860 Login`
    if [ "$admID" = "" ]; then
        admID="Admin"
    fi
    echo "ssh     stream  tcp     nowait  $admID    /bin/dropbear       /bin/dropbear -i" > /etc/inetd.conf
    /sbin/inetd
}

stop() {
 echo "Stopping inetd: "
 killall -q inetd
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
