#!/bin/sh

start() {
get_param
echo "Generate resolve: "
    #in case no previous file
    if [ $fname = "" ]; then
	fname = "/etc/resolv.conf"
    fi
    if [ -f $fname ]; then
        touch $fname
    fi

    # backup file without nameserver part
    sed -e '/nameserver/d' $fname > $fbak

    # set primary and seconday DNS
    if [ "$pd" != "" ]; then
      echo "nameserver $pd" > $fname
    else
      # empty dns
      rm -f $fname
    fi
    if [ "$sd" != "" ]; then
      echo "nameserver $sd" >> $fname
    fi
    # if nameservers is null add 127.0.0.1
    if  [ "$pd" = "" ] && [ "$sd" = "" ]; then
      echo "nameserver 127.0.0.1" > $fname
    fi

    cat $fbak >> $fname
    rm -f $fbak
}

stop() {
 echo " "
}

get_param() {
    admID=`nvram_get 2860 Login`
    pd=`nvram_get 2860 wan_primary_dns`
    sd=`nvram_get 2860 wan_secondary_dns`
    fname="/etc/resolv.conf"
    fbak="/etc/resolv_conf.bak"
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
