#!/bin/sh

# if app not exist
if [ ! -f /sbin/inetd ]; then
    exit 0
fi

LOG="logger -t inetd"

start() {
    get_param
    if [ "$Login" != "" ]; then
	echo > /etc/inetd.conf
	need_start=0
	if [ -f /bin/dropbear ] && [ "$RemoteSSH" != "" ] && [ "$RemoteSSH" != "0" ]; then
	    echo "ssh stream tcp nowait $Login /bin/dropbear /bin/dropbear -i -K60 -I360 -m" >> /etc/inetd.conf
	    need_start=1
	fi
	if [ -f /bin/ftpd ]; then
	    echo "ftp stream tcp nowait $Login /bin/ftpd ftpd -q" >> /rwfs/inetd.conf
	    need_start=1
	fi
	if [ -f /bin/telnetd ]; then
	    echo "telnet stream tcp nowait $Login /bin/telnetd telnetd -i" >> /rwfs/inetd.conf
	    need_start=1
	fi
	if [ "$need_start" = "1" ]; then
	    $LOG "Starting inetd"
    	    /sbin/inetd -R 30 -q 64
	fi
    fi
}

stop() {
 $LOG "Stopping inetd"
 killall -q inetd
 killall -q -9 inetd
}

get_param() {
 Login=`nvram_get 2860 Login`
 RemoteSSH=`nvram_get 2860 RemoteSSH`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
