#!/bin/sh

start() {
    if [ -f /sbin/inetd ]; then
      echo "Starting inetd: "
	admID=`nvram_get 2860 Login`
	if [ "$admID" = "" ]; then
    	    admID="Admin"
	fi
	if [ -f /bin/dropbear ]; then
	    echo "ssh     stream  tcp     nowait  $admID    /bin/dropbear       /bin/dropbear -i -K60 -I360 -m" > /etc/inetd.conf
	fi
        /sbin/inetd
    fi
}

stop() {
 echo "Stopping inetd: "
 killall -q inetd
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
