#!/bin/sh

LOG="logger -t sysctl"

start() {
    $LOG "Tune kernel with sysctl."
    sysctl -w -p /etc/sysctl.conf > /dev/null 2>&1

    MINPORT=3072
    if [ -f /tmp/is_32ram_dev ]; then
	#conntrack table size set coherent to foetable
	if [ "$CONFIG_RA_HW_NAT_TBL_1K" != "" ]; then
    	    CONNTRACK_MAX=1024
	elif [ "$CONFIG_RA_HW_NAT_TBL_2K" != "" ]; then
    	    CONNTRACK_MAX=2048
	elif [ "$CONFIG_RA_HW_NAT_TBL_4K" != "" ]; then
    	    CONNTRACK_MAX=4096
	elif [ "$CONFIG_RA_HW_NAT_TBL_8K" != "" ]; then
    	    CONNTRACK_MAX=8192
	elif [ "$CONFIG_RA_HW_NAT_TBL_16K" != "" ]; then
    	    CONNTRACK_MAX=16384
	else
    	    CONNTRACK_MAX=4096
	fi
        let "HASHSIZE=$CONNTRACK_MAX/2"
        let "ROUTEMAX=$CONNTRACK_MAX*4"
	sysctl -w vm.min_free_kbytes=2304
    else
        CONNTRACK_MAX=1024
        let "HASHSIZE=$CONNTRACK_MAX/4"
        let "ROUTEMAX=$CONNTRACK_MAX"
	sysctl -w vm.min_free_kbytes=896
    fi
    let "MAXPORT=$MINPORT+$CONNTRACK_MAX*2"
    let "CONNGEN=$CONNTRACK_MAX-400"

    if [ -f /sys/module/nf_conntrack/parameters/hashsize ]; then
        echo $HASHSIZE > /sys/module/nf_conntrack/parameters/hashsize
	sysctl -w net.netfilter.nf_conntrack_max=$CONNTRACK_MAX
	sysctl -w net.nf_conntrack_max=$CONNTRACK_MAX
    else
	sysctl -w net.ipv4.ip_conntrack_max=$CONNTRACK_MAX
    fi

    sysctl -w net.general_conntrack_max=$CONNGEN
    sysctl -w net.ipv4.netfilter.ip_conntrack_max=$CONNTRACK_MAX
    sysctl -w net.ipv4.route.max_size=$ROUTEMAX
    sysctl -w net.ipv4.ip_local_port_range="$MINPORT $MAXPORT"

    $LOG "##conntrack table max:$CONNTRACK_MAX##hashsize:$HASHSIZE##"
    $LOG "##route table max:$ROUTEMAX##portrange:$MINPORT $MAXPORT##"

    $LOG "Tune with proc proc"
    # on kernel crash
    echo 1    > /proc/sys/kernel/panic
    echo 1    > /proc/sys/kernel/panic_on_oops
    echo 1    > /proc/sys/vm/panic_on_oom

###################### SECTION FOR SAMBA AND TRANSMISION KERNEL TUNE ###################
    SmbEnabled=`nvram_get 2860 SmbEnabled`
    TransmissionEnabled=`nvram_get 2860 TransmissionEnabled`
    if [ "$SmbEnabled" = "1" ] || [ "$TransmissionEnabled" = "1" ]; then
	# banish core dump files to /dev/null
	ulimit -c 0
	# increase file descriptors
	ulimit -n 32768
	# virtual memory
	ulimit -v unlimited
	# max memory size
	ulimit -m unlimited
	# increase memlimits
        echo "524288" > /proc/sys/net/core/wmem_max
        echo "2097152" > /proc/sys/net/core/rmem_max
	# more mem reserved
	sysctl -w vm.min_free_kbytes=3192
    fi
    if [ -f /tmp/is_16ram_dev ] || [ "$SmbEnabled" = "1" ] || [ "$TransmissionEnabled" = "1" ]; then
	# enable overcommit memory
	sysctl -w vm.overcommit_memory=1
    fi
########################################################################################
}

stop() {
    echo "" > /dev/null
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
