#!/bin/sh

start() {
 echo "Tune with sysctl: "
    sysctl -w -p /etc/sysctl.conf > /dev/null 2>&1

  echo "Tune network stack and memory usadge fo small memory devices"
    # tcp buff size
    MAX_MEM=`free | grep Total | awk '{ print ($4-1228)*1024 }'`
    CMAX_MEM=`echo $MAX_MEM | awk '{ print ($1)/2 }' | cut -d '.' -f1`
    CORE_MEM=`echo $MAX_MEM | awk '{ print ($1)/4 }' | cut -d '.' -f1`
    IPV4_MEM=`echo $MAX_MEM | awk '{ print ($1)/6 }' | cut -d '.' -f1`
    # set sysctl
    sysctl -w net.core.rmem_max=$CMAX_MEM
    sysctl -w net.core.wmem_max=$CMAX_MEM
    sysctl -w net.ipv4.tcp_rmem="4096 43689 $CORE_MEM"
    sysctl -w net.ipv4.tcp_wmem="4096 16384 $CORE_MEM"
    sysctl -w net.ipv4.tcp_mem="2048 2560 $IPV4_MEM"

    MEM_SIZE=`free | grep Total | awk '{ print $2/10000 }' | cut -d '.' -f1`                                                 
    MINPORT=3072
    if [ "$MEM_SIZE" = "1" ]; then                                                                                             
        #16mb                                                                                                                
        CONNTRACK_MAX=2048                                                                                                   
        let "HASHSIZE=$CONNTRACK_MAX/8"
        let "ROUTEMAX=$CONNTRACK_MAX*12"
	let "MAXPORT=$MINPORT+$CONNTRACK_MAX*2"
    else                                                                                                                     
        #32mb                                                                                                                
        CONNTRACK_MAX=2304                                                                                                   
        let "HASHSIZE=$CONNTRACK_MAX/4"
        let "ROUTEMAX=$CONNTRACK_MAX*14"
	let "MAXPORT=$MINPORT+$CONNTRACK_MAX*2"
    fi                                                                                                                       

    if [ -f /sys/module/nf_conntrack/parameters/hashsize ]; then
        echo $HASHSIZE > /sys/module/nf_conntrack/parameters/hashsize
	sysctl -w net.netfilter.nf_conntrack_max=$CONNTRACK_MAX
	sysctl -w net.nf_conntrack_max=$CONNTRACK_MAX
    else
	sysctl -w net.ipv4.ip_conntrack_max=$CONNTRACK_MAX
    fi

    sysctl -w net.ipv4.netfilter.ip_conntrack_max=$CONNTRACK_MAX
    sysctl -w net.ipv4.route.max_size=$ROUTEMAX
    sysctl -w net.ipv4.ip_local_port_range="$MINPORT $MAXPORT"

    echo "##conntrack max:##hashsize:##route max:##route max:##portrange:"
    echo "##$CONNTRACK_MAX##$HASHSIZE##$ROUTEMAX##$MINPORT $MAXPORT"

    echo "Tune with proc"
    #memory
    echo 1500  > /proc/sys/vm/min_free_kbytes
    echo 128  > /proc/sys/kernel/threads-max
    echo 1    > /proc/sys/vm/page-cluster
    echo 0    > /proc/sys/vm/overcommit_ratio
    echo 0    > /proc/sys/vm/overcommit_memory
    #on kernel crash
    echo 1    > /proc/sys/kernel/panic
    echo 1    > /proc/sys/kernel/panic_on_oops
    echo 1    > /proc/sys/vm/panic_on_oom
}

stop() {
 echo "Stopping sysctl: "
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
