#!/bin/sh

LOG="logger -t WATCHDOG"

start() {
    WatchdogEnabled=`nvram_get 2860 WatchdogEnabled`
    if [ "$WatchdogEnabled" = "1" ]; then
	$LOG "Start watchdog"
	nice --19 watchdog -T 120 -t 10 -F /dev/watchdog  > /dev/null 2>&1 &
    fi
}

stop() {
 $LOG "Stop watchdog"
    killall -q watchdog
    killall -q -9 watchdog
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
