#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t WAN"

start() {
 $LOG "Start wan config"

    get_param
    $LOG "Configure WAN."

    #stop dhcp client
    killall -q udhcpc
    killall -q -9 udhcpc

    #Flush conntrack table and route cache
    echo 1 > /proc/sys/net/nf_conntrack_flush
    ip route flush cache

    getHostName
    /bin/hostname $HOSTNAME
    echo "127.0.0.1	localhost $HOSTNAME.lo" > /etc/hosts
    echo "$lan_ip	$HOSTNAME.lo" >> /etc/hosts
    echo "$wan_ip	$HOSTNAME.lo" >> /etc/hosts
    # read for all write by root
    chmod 644 /etc/hosts > /dev/null 2>&1

    if [ "$opmode" != "0" ] && [ "$vpnPurePPPOE" != "1" ]; then
	if [ "$wan_manual_mtu" != "0" ] && [ "$wan_manual_mtu" != "" ]; then
	    $LOG "Set manual MTU to WAN $wan_manual_mtu"
	    ip link set mtu $wan_manual_mtu dev $wan_if
	fi
    fi
    if [ "$opmode" != "0" ] && [ "$vpnEnabled" = "on" ] && [ "$vpnType" = "0" ] && [ "$vpnPurePPPOE" = "1" ]; then
	    $LOG "PURE PPPOE Mode. Do need start dhcpc or config wan!"
	    ip addr flush dev $wan_if
	    ip link set $wan_if up
	    exit 0
    fi

    if [ "$wanmode" = "STATIC" ] || [ "$opmode" = "0" ]; then
	if [ "$opmode" != "0" ]; then
	    #lan and wan ip should not be the same except in bridge mode
	    if [ "$wan_ip" = "$lan_ip" ]; then
		$LOG "wan service: warning: WAN's IP address is set identical to LAN"
		exit 0
	    fi
	    #wan interface up and default gateway
	    ifconfig $wan_if $wan_ip netmask $wan_nm
	    #always treat bridge mode having static wan connection
	    #route mode
	    if [ "$gw" != "" ] && [ "$gw" != "0.0.0.0" ]; then
		ip route replace default via $gw
	    fi
	else
	    #wan interface up and default gateway
	    ifconfig br0 $lan_ip netmask $lan_nm
	    #if bridge mode dgw on dev br0 set
	    if [ "$gw" != "" ] && [ "$gw" != "0.0.0.0" ]; then
    		ip route replace default dev br0 via $gw
	    else
    		ip route replace default dev br0
	    fi
        fi
    else
	#reload global
	. /etc/scripts/global.sh

	#wait sta connected
	wait_connect

	#get udhcp param
	udhcpc_opts

	$LOG "Start DHCP client."
	(sleep $CL_SLEEP && udhcpc $UDHCPCOPTS > /dev/null 2>&1) &
    fi
}

stop() {
 echo "" > /dev/null
}

get_param() {
    #get parametrs
    wan_manual_mtu=`nvram_get 2860 wan_manual_mtu`
    vpnPurePPPOE=`nvram_get 2860 vpnPurePPPOE`
    clone_en=`nvram_get 2860 macCloneEnabled`
    clone_mac=`nvram_get 2860 macCloneMac`
    wan_ip=`nvram_get 2860 wan_ipaddr`
    wan_nm=`nvram_get 2860 wan_netmask`
    lan_ip=`nvram_get 2860 lan_ipaddr`
    lan_nm=`nvram_get 2860 lan_netmask`
    gw=`nvram_get 2860 wan_gateway`
    wanmode=`nvram_get 2860 wanConnectionMode`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
