#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

LOG="echo WAN: "

start() {
 $LOG "Start wan config"

    get_param

    $LOG "Configure WAN."

    #stop dhcp client
    killall -q udhcpc
    killall -q -9 udhcpc

    #Flush conntrack table and route cache
    echo 1 > /proc/sys/net/nf_conntrack_flush
    ip route flush cache

    /bin/hostname $HOSTNAME
    echo "127.0.0.1	localhost $HOSTNAME.lo" > /etc/hosts
    echo "$lan_ip	$HOSTNAME.lo" >> /etc/hosts
    echo "$wan_ip	$HOSTNAME.lo" >> /etc/hosts

    if [ "$wanmode" = "STATIC" ] || [ "$opmode" = "0" ]; then
	if [ "$opmode" != "0" ]; then
	    #lan and wan ip should not be the same except in bridge mode
	    if [ "$wan_ip" = "$lan_ip" ]; then
		$LOG "wan service: warning: WAN's IP address is set identical to LAN"
		exit 0
	    fi
	    #wan interface up and default gateway
	    ifconfig $wan_if $wan_ip netmask $wan_nm
	    #always treat bridge mode having static wan connection
	    #route mode
	    if [ "$gw" != "" ] && [ "$gw" != "0.0.0.0" ]; then
		ip route replace default via $gw
	    fi
	else
	    #wan interface up and default gateway
	    ifconfig br0 $lan_ip netmask $lan_nm
	    #if bridge mode dgw on dev br0 set
	    if [ "$gw" != "" ] && [ "$gw" != "0.0.0.0" ]; then
    		ip route replace default dev br0 via $gw
	    else
    		ip route replace default dev br0
	    fi
        fi
    else
	#reload global
	. /etc/scripts/global.sh

	#wait sta connected
	wait_connect

	$LOG "Start DHCP client."
	(sleep $CL_SLEEP && udhcpc $UDHCPCOPTS > /dev/null 2>&1) &
    fi

    #----Direct pass from kernel--------------------------------
    if [ "$pppoe_pass" = "1" ]; then
	echo "$lan_if,$wan_if" > /proc/pthrough/pppoe
    else
	echo "null,null" > /proc/pthrough/pppoe
    fi
    if [ "$ipv6_pass" = "1" ]; then
	echo "$lan_if,$wan_if" > /proc/pthrough/ipv6
    else
	echo "null,null" > /proc/pthrough/ipv6
    fi
    #----Fastpath for nat enable--------------------------------
    if [ "$natFastpath" != "0" ]; then
	sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=1
    else
	sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=0
    fi

}

stop() {
 echo "" > /dev/null
}

get_param() {
    #get parametrs
    clone_en=`nvram_get 2860 macCloneEnabled`
    clone_mac=`nvram_get 2860 macCloneMac`
    wan_ip=`nvram_get 2860 wan_ipaddr`
    wan_nm=`nvram_get 2860 wan_netmask`
    lan_ip=`nvram_get 2860 lan_ipaddr`
    lan_nm=`nvram_get 2860 lan_netmask`
    gw=`nvram_get 2860 wan_gateway`
    vpnEnabled=`nvram_get 2860 vpnEnabled`
    pppoe_pass=`nvram_get 2860 pppoe_pass`
    ipv6_pass=`nvram_get 2860 ipv6_pass`
    natFastpath=`nvram_get 2860 natFastpath`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
