#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

 LOG="echo IPTABLES: "

start() {
 $LOG "Starting IPTABLES: "
 get_param
#########################################DEFAULTRULES###################################
	#default filters
	$LOG "Set default filters"
	iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
###########################################IGMP-RULES#######################################
	#only eth2.2 WAN interface recived multicast
	if [ "$OperationMode" != "0" ]; then    
	    #INPUT needed by unpxy and igmpproxy
	    if [ "$igmpen" != "0" ] || [ "$UDPXY" != "0" ]; then
		$LOG "Set igmp input rules"
		iptables -A INPUT -p igmp -i $lan_if -j ACCEPT
	        iptables -A INPUT -d 224.0.0.0/4 -i eth2.2 -j ACCEPT
		iptables -A INPUT -s 224.0.0.0/4 -i eth2.2 -j ACCEPT
	    fi
	    #FORWARD rules needed only for igmpproxy.
	    if [ "$igmpen" != "0" ]; then
		$LOG "Set igmp forward rules"
		iptables -A FORWARD -d 224.0.0.0/4 -o $lan_if -j ACCEPT
		iptables -A FORWARD -s 224.0.0.0/4 -i $lan_if -j ACCEPT
	    fi
	fi

###########################################SERVICES#######################################
	$LOG "Service limit set"
        #add limit connection rules for local services
	iptables -N servicelimit > /dev/null 2>&1
        iptables -F servicelimit > /dev/null 2>&1
        iptables -A INPUT -j servicelimit > /dev/null 2>&1

	#web limit
	if [ "$RemoteManagement" != "0" ]; then
    	    iptables -A servicelimit -p tcp --dport 80 -m connlimit --connlimit-above 8 -j REJECT
	    if [ "$RemoteManagement" = "1" ]; then
		if [ "$OperationMode" != "0" ]; then
    		    iptables -A servicelimit -i $wan_if -p tcp --dport 80 -j DROP
    		    iptables -A servicelimit -i ppp+ -p tcp --dport 80 -j DROP
		fi
    		iptables -A servicelimit -i $lan_if -p tcp --dport 80 -j ACCEPT
	     if [ "$Lan2Enabled" = "1" ]; then
    		iptables -A servicelimit -i $lan2_if -p tcp --dport 80 -j ACCEPT
	     fi
	    elif [ "$RemoteManagement" = "2" ]; then
    		iptables -A servicelimit -p tcp --dport 80 -j ACCEPT
	    fi
	else	    
    	    iptables -A servicelimit -p tcp --dport 80 -j DROP
	fi
	#ssh limit
	if [ "$RemoteSSH" != "0" ]; then
    	    iptables -A servicelimit -p tcp --dport 22 -m connlimit --connlimit-above 4 -j REJECT
	    if [ "$RemoteSSH" = "1" ]; then
		if [ "$OperationMode" != "0" ]; then
    		    iptables -A servicelimit -i $wan_if -p tcp --dport 22 -j DROP
    		    iptables -A servicelimit -i ppp+ -p tcp --dport 22 -j DROP
		fi
    		iptables -A servicelimit -i $lan_if -p tcp --dport 22 -j ACCEPT
	     if [ "$Lan2Enabled" = "1" ]; then
    		iptables -A servicelimit -i $lan2_if -p tcp --dport 22 -j ACCEPT
	     fi
	    elif [ "$RemoteSSH" = "2" ]; then
    		iptables -A servicelimit -p tcp --dport 22 -j ACCEPT
	    fi
	else	    
    	    iptables -A servicelimit -p tcp --dport 22 -j DROP
	fi
	#udpxy limit
	if [ "$UDPXY" != "0" ]; then
    	    iptables -A servicelimit -p tcp --dport 81 -m connlimit --connlimit-above 8 -j REJECT
	    if [ "$UDPXY" = "1" ]; then
		if [ "$OperationMode" != "0" ]; then
    		    iptables -A servicelimit -i $wan_if -p tcp --dport 81 -j DROP
    		    iptables -A servicelimit -i ppp+ -p tcp --dport 81 -j DROP
		fi
    		iptables -A servicelimit -i $lan_if -p tcp --dport 81 -j ACCEPT
	     if [ "$Lan2Enabled" = "1" ]; then
    		iptables -A servicelimit -i $lan2_if -p tcp --dport 81 -j ACCEPT
	     fi
	    elif [ "$UDPXY" = "2" ]; then
    		iptables -A servicelimit -p tcp --dport 81 -j ACCEPT
	    fi	    
	else	    
    	    iptables -A servicelimit -p tcp --dport 81 -j DROP
	fi
	#samba
	if [ "$SmbEnabled" = "1" ]; then
	    iptables -A servicelimit -i $lan_if -p udp --dport 137:138 -j ACCEPT
	    iptables -A servicelimit -i $lan_if -p tcp --dport 139 -j ACCEPT
	else
	    iptables -A servicelimit -i $lan_if -p udp --dport 137:138 -j DROP
	    iptables -A servicelimit -i $lan_if -p tcp --dport 139 -j DROP
	fi
        #icmp limit
	if [ "$WANPingFilter" = "0" ]; then
	    if [ "$OperationMode" != "0" ]; then
		$LOG "Drop ping from wan $wan_if"
    		iptables -A servicelimit -i $wan_if -p icmp --icmp-type echo-request -j DROP
    		iptables -A servicelimit -i $wan_if -p icmp --icmp-type echo-reply -j DROP
    		iptables -A servicelimit -i ppp+ -p icmp --icmp-type echo-request -j DROP
    		iptables -A servicelimit -i ppp+ -p icmp --icmp-type echo-reply -j DROP
    		iptables -A servicelimit -i ppp+ -p icmp -j DROP
	    fi
	else
	    $LOG "Allow ping from wan $wan_if"
	fi
	iptables -A servicelimit -p icmp --icmp-type echo-request -m limit --limit 10/s -j RETURN
	iptables -A servicelimit -p icmp --icmp-type echo-request -j DROP
###########################################VPN-RULES##########################################
	if [ "$vpnEnabled" = "on"  ]; then
	    $LOG "Add vpnfilter rules"
	    if [ "$vpnType" = "1"  ]; then
		iptables -A servicelimit -p gre -j ACCEPT
		iptables -A servicelimit -p tcp --sport 1723 -j ACCEPT
	    elif [ "$vpnType" = "2"  ]; then
		iptables -A servicelimit -p udp --sport 500 -j ACCEPT
		iptables -A servicelimit -p udp --dport 500 -j ACCEPT
		iptables -A servicelimit -p udp --sport 1701 -j ACCEPT
		iptables -A servicelimit -p udp --dport 1701 -j ACCEPT
		iptables -A servicelimit -p udp --sport 4500 -j ACCEPT
		iptables -A servicelimit -p udp --dport 4500 -j ACCEPT
	    fi
	fi
###########################################FORWARD#######################################
	if [ "$OperationMode" != "0" ]; then
	    $LOG "Set forward rules"
            #enable forward for all interfaces
	    sysctl -w net.ipv4.ip_forward=1
	    #accept my packets
	    iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
	    #tune mss size for tranzit packets
	    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

	    if [ "$IPPortFilterEnable" = "1" ] && [ -f /etc/macipfilter ]; then    
		$LOG "Set macipport_filter rules"
		chmod 777 /etc/macipfilter
		/etc/macipfilter
		if [ "$DefaultFirewallPolicy" = "1" ]; then
		    $LOG "Default policy macipport_filter DROP"
		    iptables -t filter -A macipport_filter -j DROP
		else
		    $LOG "Default policy macipport_filter ACCEPT"
		    iptables -t filter -A macipport_filter -j ACCEPT
		fi
	    fi

	    if [ -f /etc/websfilter ]; then
        	$LOG "Add rules for content filters"
		modprobe -q xt_webstr
		chmod 777 /etc/websfilter
    		/etc/websfilter
	    fi

	    #enable forward only from local network to wan/ppp
	    iptables -A FORWARD -i $lan_if -s $lan_ip/$lan_nm -j ACCEPT
	    iptables -A FORWARD -o $wan_if -s $lan_ip/$lan_nm -j ACCEPT
	    iptables -A FORWARD -o ! $lan_if -s $lan_ip/$lan_nm -j ACCEPT
	    #second lan
	    if [ "$Lan2Enabled" = "1" ]; then
    		iptables -A FORWARD -o ! $lan_if -s $lan2_ipaddr/$lan2_netmask -j ACCEPT
	    fi
	fi

###########################################NAT-NAPTM#######################################
	#masqrade for wan interfaces
	if [ "$NAT" = "1" ] || [ "$vpnNAT" != "off" ]; then
	    $LOG "Add masqrade rules"
	    if [ -f /etc/portforward ] && [ "$PortForwardEnable" = "1" ]; then
		$LOG "Add portforward rules"
		chmod 777 /etc/portforward
		/etc/portforward
	    fi
	    #######################DMZ##################################
	    if [ "$DMZEnable" = "1" ] && [ "$DMZIPAddress" != "" ]; then
		iptables -t nat -N DMZ
		iptables -t nat -A PREROUTING -j DMZ
		$LOG "DMZ enabled for $DMZIPAddress"
		iptables -t nat -A DMZ -j DNAT -i ! $lan_if -s ! $lan_ip/$lan_nm --to $DMZIPAddress
		iptables -A FORWARD -i ! $lan_if -d $DMZIPAddress -j ACCEPT
	    fi

	  if [ "$OperationMode" != "0" ] && [ "$NAT" = "1" ]; then
	    #for ISP localnet alya dualacess
    	    iptables -t nat -A POSTROUTING -o eth2.2  -s $lan_ip/$lan_nm -j MASQUERADE
	    #wireless ISP net dual dual acess....gyyy
	    iptables -t nat -A POSTROUTING -o ra+     -s $lan_ip/$lan_nm -j MASQUERADE
	    iptables -t nat -A POSTROUTING -o apcli+  -s $lan_ip/$lan_nm -j MASQUERADE
	    
	    #second lan
	    if [ "$Lan2Enabled" = "1" ]; then
		#for ISP localnet alya dualacess
    		iptables -t nat -A POSTROUTING -o eth2.2  -s $lan2_ipaddr/$lan2_netmask -j MASQUERADE
		#wireless ISP net dual dual acess....gyyy
		iptables -t nat -A POSTROUTING -o ra+     -s $lan2_ipaddr/$lan2_netmask -j MASQUERADE
		iptables -t nat -A POSTROUTING -o apcli+  -s $lan2_ipaddr/$lan2_netmask -j MASQUERADE
	    fi
	 fi
	fi
###########################################UPNPRULES#######################################
        #rules for upnp
	if [ "$upnp" = "1" ] && [ "$OperationMode" != "0" ]; then
            iptables -t nat -N MINIUPNPD
            iptables -t nat -F MINIUPNPD
            iptables -t nat -A PREROUTING -i $wan_upnp_if -j MINIUPNPD
            iptables -t filter -N MINIUPNPD
            iptables -t filter -F MINIUPNPD
            iptables -t filter -A FORWARD -i $wan_upnp_if -o ! $wan_ppp_if -j MINIUPNPD
        fi
############################################VPNRULES#######################################
	if [ -f /etc/ppp_firewall ] && [ "$vpnEnabled" = "on"  ]; then
	    $LOG "Call to add VPN netfilter rules"
	    /etc/ppp_firewall
	fi
############################################ENDRULES#######################################
	$LOG "Iptables rules add OK..."
}


stop() {
 $LOG "Stopping IPTABLES: "
	iptables -F > /dev/null 2>&1
	iptables -t nat -F > /dev/null 2>&1
        iptables -t filter -F > /dev/null 2>&1
        iptables -t mangle -F > /dev/null 2>&1
        iptables -X > /dev/null 2>&1
        iptables -t nat -X > /dev/null 2>&1
        iptables -t filter -X > /dev/null 2>&1
        iptables -t mangle -X > /dev/null 2>&1

        iptables -t mangle -F PREROUTING > /dev/null 2>&1
        iptables -t mangle -F FORWARD > /dev/null 2>&1
        iptables -t mangle -F INPUT > /dev/null 2>&1
        iptables -t mangle -F OUTPUT > /dev/null 2>&1
        iptables -t mangle -F POSTROUTING > /dev/null 2>&1

        iptables -t nat -Z > /dev/null 2>&1
        iptables -t filter -Z > /dev/null 2>&1
        iptables -t mangle -Z > /dev/null 2>&1
	iptables -Z > /dev/null 2>&1

	#default actions
	iptables -P FORWARD DROP > /dev/null 2>&1
	iptables -P INPUT ACCEPT > /dev/null 2>&1
	iptables -P OUTPUT ACCEPT > /dev/null 2>&1

}

get_param() {
    lan_ip=`nvram_get 2860 lan_ipaddr`
    lan_nm=`nvram_get 2860 lan_netmask`
    Lan2Enabled=`nvram_get 2860 Lan2Enabled`
    lan2_ipaddr=`nvram_get 2860 lan2_ipaddr`
    lan2_netmask=`nvram_get 2860 lan2_netmask`
    OperationMode=`nvram_get 2860 OperationMode`
    upnp=`nvram_get 2860 upnpEnabled`
    WANPingFilter=`nvram_get 2860 WANPingFilter`
    PortForwardEnable=`nvram_get 2860 PortForwardEnable`
    NAT=`nvram_get 2860 natEnabled`
    igmpen=`nvram_get 2860 igmpEnabled`
    vpnEnabled=`nvram_get 2860 vpnEnabled`
    vpnType=`nvram_get 2860 vpnType`
    vpnNAT=`nvram_get 2860 vpnNAT`
    UDPXY=`nvram_get 2860 UDPXYMode`
    RemoteSSH=`nvram_get 2860 RemoteSSH`
    RemoteManagement=`nvram_get 2860 RemoteManagement`
    DMZEnable=`nvram_get 2860 DMZEnable`
    DMZIPAddress=`nvram_get 2860 DMZIPAddress`
    DefaultFirewallPolicy=`nvram_get 2860 DefaultFirewallPolicy`
    IPPortFilterEnable=`nvram_get 2860 IPPortFilterEnable`
    SmbEnabled=`nvram_get 2860 SmbEnabled`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
