#!/bin/sh

start() {
 echo "Starting crontab: "
 /sbin/crond -l 0 -L /var/log/cron.log
}

stop() {
 echo "Stopping crontab: "
 killall crond > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
