#!/bin/sh

#get params
. /sbin/global.sh

start() {
if [ -f /bin/pppoe-relay ]; then
 echo "Starting pppoe-relay: "
    pppr=`nvram_get 2860 pppoeREnabled`
    if [ "$pppr" = "1" ]; then
        pppoe-relay -S $wan_if -B $lan_if
    fi
fi
}

stop() {
 echo "Stopping pppoe-relay: "
    killall pppoe-relay > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
