#!/bin/sh

# if app not exist
if [ ! -f /bin/pppoe-relay ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

if [ "$opmode" = "0" ]; then
    exit 0
fi

LOG="logger -t pppoerelay"

start() {
    pppr=`nvram_get 2860 pppoeREnabled`
    if [ "$pppr" = "1" ]; then
	$LOG "Starting pppoe-relay"
        pppoe-relay -S $wan_if -B $lan_if
    fi
}

stop() {
 $LOG "Stopping pppoe-relay"
    killall -q pppoe-relay
    killall -q -9 pppoe-relay
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
