#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/lld2d ]; then
 echo "Starting LLD2D: "
    lltd=`nvram_get 2860 lltdEnabled`
    if [ "$lltd" = "1" ]; then
        lld2d $lan_if
    fi
fi
}

stop() {
 echo "Stopping LLD2D: "
  killall -q lld2d
  rm -rf /var/run/lld2d-* > /dev/null 2>&1
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
