#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

LOG="echo LLD2D: "

start() {
    get_param
    if [ -f /bin/lld2d ] && [ "$lltd" = "1" ]; then
	$LOG "Starting LLD2D: "
	lld2d $lan_if
    fi
}

stop() {
 $LOG "Stopping LLD2D: "
  killall -q lld2d
  killall -q -9 lld2d
  rm -rf /var/run/lld2d-* > /dev/null 2>&1
}

get_param() {
    lltd=`nvram_get 2860 lltdEnabled`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
