#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
	dhcp=`nvram_get 2860 dhcpEnabled`
	if [ "$dhcp" = "1" ]; then
	    echo "Start dhcpserver "
		start=`nvram_get 2860 dhcpStart`
		end=`nvram_get 2860 dhcpEnd`
		mask=`nvram_get 2860 dhcpMask`
		pd=`nvram_get 2860 dhcpPriDns`
		sd=`nvram_get 2860 dhcpSecDns`
		gw=`nvram_get 2860 dhcpGateway`
		lease=`nvram_get 2860 dhcpLease`
		static1=`nvram_get 2860 dhcpStatic1`

		> /etc/udhcpd.conf
		> /var/udhcpd.leases

		config-udhcpd.sh -s $start
		config-udhcpd.sh -e $end
		config-udhcpd.sh -i $lan_if
		config-udhcpd.sh -m $mask

		if [ "$pd" != "" -o "$sd" != "" ]; then
			config-udhcpd.sh -d $pd $sd
		fi
		if [ "$gw" != "" ]; then
			config-udhcpd.sh -g $gw
		fi
		if [ "$lease" != "" ]; then
			config-udhcpd.sh -t $lease
		fi

		# Write static DHCP leases
		if [ -e /etc/dhcpd_static.conf ]; then
			cat /etc/dhcpd_static.conf | while read line; do
				config-udhcpd.sh -S $line;
			done;
		fi

		config-udhcpd.sh -r
	fi
}

stop() {
	echo "Stop dhcpserver "
	killall -q udhcpd
}

case "$1" in
	start)
		start
		;;

	stop)
		stop
		;;

	restart)
		stop
		start
		;;

	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac
