#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t dhcpd"

start() {
	dhcpEnabled=`nvram_get 2860 dhcpEnabled`
	if [ "$dhcpEnabled" = "1" ]; then
	    $LOG "Start dhcpserver"
	    get_param

		> /etc/udhcpd.conf
		touch /var/udhcpd.dhcpLeases

		config-udhcpd.sh -s "$dhcpStart"
		config-udhcpd.sh -e "$dhcpEnd"
		config-udhcpd.sh -i "$lan_if"
		config-udhcpd.sh -m "$dhcpMask"

		if [ "$dnsPEnabled" = "1" ]; then
		    # use dnsmasq for relay
		    config-udhcpd.sh -d "$lan_ipaddr" "$lan_ipaddr"
		else
		    # client direct to dns
		    if [ "$wan_static_dns" = "on" ]; then
			if [ "$dhcpPriDns" != "" ] || [ "$dhcpSecDns" != "" ]; then
			    config-udhcpd.sh -d "$dhcpPriDns" "$dhcpSecDns"
			else
			    config-udhcpd.sh -d "8.8.8.8" "8.8.4.4"
			fi
		    else
			pd=`grep nameserver < /etc/resolv.conf | tail -q -n1 | awk {' print $2 '}`
                        if [ "$dhcpPriDns" != "" ]; then
			    config-udhcpd.sh -d "$dhcpPriDns"
			else
			    config-udhcpd.sh -d "8.8.8.8" "8.8.4.4"
			fi
		    fi
		fi

		if [ "$dhcpGateway" != "" ]; then
			config-udhcpd.sh -g "$dhcpGateway"
		fi
		if [ "$dhcpLease" != "" ]; then
			config-udhcpd.sh -t "$dhcpLease"
		fi
		if [ "$dhcpDomain" != "" ]; then
			config-udhcpd.sh -D "$dhcpDomain"
		fi
		if [ "$SmbEnabled" = "1" ]; then
			config-udhcpd.sh -w "$lan_ipaddr"
		fi

		# Write static DHCP leases
		if [ -e /etc/dhcpd_static.conf ]; then
			cat /etc/dhcpd_static.conf | while read line; do
				config-udhcpd.sh -S $line;
			done;
		fi
		config-udhcpd.sh -r

	elif [ "$dhcpEnabled" = "2" ]; then
		$LOG "Start dhcprelay"
		dhcprelay $lan_if $wan_if &
	fi
}

stop() {
	$LOG "Stop dhcpserver "
	killall -q udhcpd
	killall -q dhcprelay
	killall -q -SIGKILL udhcpd
	killall -q -SIGKILL dhcprelay
}

get_param() {
	dhcpDomain=`nvram_get 2860 dhcpDomain`
	dhcpStart=`nvram_get 2860 dhcpStart`
	dhcpEnd=`nvram_get 2860 dhcpEnd`
	dhcpMask=`nvram_get 2860 dhcpMask`
	dhcpPriDns=`nvram_get 2860 dhcpPriDns`
	dhcpSecDns=`nvram_get 2860 dhcpSecDns`
	dhcpGateway=`nvram_get 2860 dhcpGateway`
	dhcpLease=`nvram_get 2860 dhcpLease`
	dhcpStatic1=`nvram_get 2860 dhcpStatic1`
	lan_ipaddr=`nvram_get 2860 lan_ipaddr`
	SmbEnabled=`nvram_get 2860 SmbEnabled`
	dnsPEnabled=`nvram_get 2860 dnsPEnabled`
	wan_static_dns=`nvram_get 2860 wan_static_dns`
}

case "$1" in
	start)
		start
		;;

	stop)
		stop
		;;

	restart)
		stop
		start
		;;

	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac
