#!/bin/sh

#get params
. /sbin/global.sh

wan_mode=`nvram_get 2860 wanConnectionMode`
if [ "$wan_mode" = "PPPOE" -o  "$wan_mode" = "L2TP" -o "$wan_mode" = "PPTP"  ]; then
    wan_ppp_if="ppp0"
else
    if [ "$wan_if" = "" ]; then
	wan_ppp_if="eth2.2"
    else
	wan_ppp_if=$wan_if
    fi
fi

start() {
 echo "Start upnp "
    if [ "$opmode" = "0" -o "$opmode" = "1" ]; then
        upnp=`nvram_get 2860 upnpEnabled`
        if [ "$upnp" = "1" ]; then
	    ip=`nvram_get 2860 lan_ipaddr`
	    EXTIP="`LC_ALL=C /sbin/ifconfig $wan_ppp_if | grep 'inet addr' | awk '{print $2}' | sed -e 's/.*://'`"
	    echo "External IP = $wan_ppp_if"
	    iptables -t nat -N MINIUPNPD
	    iptables -t nat -F MINIUPNPD
	    iptables -t nat -A PREROUTING -i $wan_ppp_if -j MINIUPNPD
	    iptables -t filter -N MINIUPNPD
	    iptables -t filter -F MINIUPNPD
	    iptables -t filter -A FORWARD -i $wan_ppp_if -o ! $wan_ppp_if -j MINIUPNPD
            route add -net 239.0.0.0 netmask 255.0.0.0 dev $lan_if
            miniupnpd -f /etc/miniupnpd.conf -i $wan_ppp_if -a $ip &
	fi
    fi
}

stop() {
 echo "Stop upnp "
    killall miniupnpd > /dev/null 2>&1
    iptables -t nat -F MINIUPNPD > /dev/null 2>&1
    iptables -t nat -D PREROUTING -i $wan_ppp_if -j MINIUPNPD > /dev/null 2>&1
    iptables -t nat -X MINIUPNPD > /dev/null 2>&1
    iptables -t filter -F MINIUPNPD > /dev/null 2>&1
    iptables -t filter -D FORWARD -i $wan_ppp_if -o ! $wan_ppp_if -j MINIUPNPD > /dev/null 2>&1
    iptables -t filter -X MINIUPNPD > /dev/null 2>&1
    route del -net 239.0.0.0 netmask 255.0.0.0 dev $lan_if > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
