#!/bin/sh

#get params
. /sbin/global.sh

start() {
if [ -f /bin/miniupnpd ]; then
 echo "Start upnp "
 gen_uuid
 get_param
    if [ "$opmode" = "0" -o "$opmode" = "1" ]; then
	EXTIP="`LC_ALL=C /sbin/ifconfig $wan_upnp_if | grep 'inet addr' | awk '{print $2}' | sed -e 's/.*://'`"
        if [ "$upnp" = "1" ] && [ "$EXTIP" != "" ]; then
	    echo "External IP = $EXTIP"
            route add -net 239.0.0.0 netmask 255.0.0.0 dev $lan_if
	    cat /etc/miniupnpd.conf.template > /etc/miniupnpd.conf 
	    cat /etc/miniupnpd.conf.uuid >> /etc/miniupnpd.conf 
            miniupnpd -f /etc/miniupnpd.conf -i $wan_upnp_if -o $EXTIP -a $ip &
	fi
    fi
fi
}

stop() {
 echo "Stop upnp "
    killall -q miniupnpd
    route del -net 239.0.0.0 netmask 255.0.0.0 dev $lan_if > /dev/null 2>&1
}

get_param() {
    ip=`nvram_get 2860 lan_ipaddr`
    upnp=`nvram_get 2860 upnpEnabled`
    wan_mode=`nvram_get 2860 wanConnectionMode`
    if [ "$wan_mode" = "PPPOE" -o  "$wan_mode" = "L2TP" -o "$wan_mode" = "PPTP"  ]; then
	wan_upnp_if="ppp0"
    else
	if [ "$wan_if" = "" ]; then
	    wan_upnp_if="eth2.2"
	else
	    wan_upnp_if=$wan_if
        fi
    fi
}
gen_uuid() {
if [ -f /etc/miniupnpd.conf.uuid ]; then
 echo "Use old UUID file"
else
   echo "Generate UUID for miniupnpd"
   num=0
    for i in `seq 1 36`; do
        id=`cat /dev/urandom | hexdump | head -1 | cut -c9`
        num=`expr $num + 1`
        if [ $num = "9" ] || [ $num = "19" ] || [ $num = "24" ]; then
            id="-"
        fi
        outid=$outid$id
    done
    echo "UPNP UUID is $outid"
    echo "uuid=""$outid" >> /etc/miniupnpd.conf.uuid
    serial=`hostid`
    echo "serial=""$serial" >> /etc/miniupnpd.conf.uuid
    fs save
fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
