#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t RIPD"

start() {
RIPEnable=`nvram_get 2860 RIPEnable`
if [ -f /bin/ripd ] && [ "$RIPEnable" = "1" ]; then
 if [ -f /etc/ripd.conf ]; then
    $LOG "Starting RIPD: "
    ripd -f /etc/ripd.conf -d
 fi 
fi
}

stop() {
 $LOG "Stopping RIPD: "
  killall -q ripd
  killall -q -9 ripd
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
