#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/ripd ]; then
 if [ -f /etc/ripd.conf ]; then
    echo "Starting RIPD: "
    ripd -f /etc/ripd.conf -d
 fi 
fi
}

stop() {
 echo "Stopping RIPD: "
  killall -q ripd
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
