#!/bin/sh

# if app not exist
if [ ! -f /bin/miniupnpd ]; then
    exit 0
fi

# wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t upnpd"

start() {
 get_param
 if [ "$upnpEnabled" != "1" ]; then
    exit 0
 fi
    if [ "$OperationMode" != "0" ] || [ "$vpnEnabled" = "on" ]; then
	if [ ! -f /var/upnp_leases ]; then
	    touch /var/upnp_leases
	fi
	already_started=`pidof miniupnpd`
	if [ "$already_started" != "" ]; then
	    killall -q miniupnpd
	    killall -q -SIGKILL miniupnpd
	    sleep 2
	fi
        if [ "$real_wan_ipaddr" != "" ]; then
	    $LOG "Start upnp at $real_wan_ipaddr"
	    ip route replace 239.0.0.0/8 dev $lan_if
	    cat /etc/miniupnpd.conf.template > /etc/miniupnpd.conf
	    cat /etc/miniupnpd.conf.uuid >> /etc/miniupnpd.conf
            miniupnpd -f /etc/miniupnpd.conf -i "$real_wan_if" -o "$real_wan_ipaddr" -a "$lan_ipaddr/$lan_netmask" &
	fi
    fi
}

stop() {
 $LOG "Stop upnp "
    killall -q miniupnpd
    killall -q -SIGKILL miniupnpd
    ip route del 239.0.0.0/8 dev "$lan_if" > /dev/null 2>&1
}

get_param() {
    eval `nvram_buf_get 2860 lan_ipaddr lan_netmask upnpEnabled`
}


case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
