#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/radvd ]; then
 echo "Starting radvd: "
    radvd=`nvram_get 2860 radvdEnabled`
    ip link set sit0 down
    echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
    if [ "$radvd" = "1" ]; then
        echo "1" > /proc/sys/net/ipv6/conf/all/forwarding
	echo "Up sit0 interface"                                                                                                 
	ip link set sit0 up                                                                                                      
	ip addr flush dev sit0                                                                                                   
	ip addr add 2002:1101:101::1101:101/16 dev sit0                                                                          
	echo "Add route sit0 interface"                                                                                          
	ip -6 route flush dev sit0                                                                                               
	ip -6 route replace 2000::/3 via 2002:c058:6301::1 dev sit0                                                              
	ip -6 route replace 2002:1101:101:0::/64 dev br0                                                                         
	echo "Add iptables rules fo ipv6"                                                                                        
	iptables -I INPUT  -p ipv6 -j ACCEPT                                                                                     
	iptables -I OUTPUT -p ipv6 -j ACCEPT                                                                                     
	iptables -I FORWARD  -p ipv6 -j ACCEPT                                                                                   
	ip6tables -A INPUT -j ACCEPT                                                                                             
	ip6tables -A FORWARD -j ACCEPT                                                                                           
	ip6tables -A OUTPUT -j ACCEPT                                                                                            
        ip6tables -F                                                                                                             
	echo "Starting radvd"                                                                                                    
	radvd -C /etc/radvd.conf -d 1 &                   
    fi
fi
}

stop() {
 echo  "Stop radvd daemon..."                                                                                               
  killall radvd > /dev/null 2>&1                                                                                             
  ip -6 route del 2000::/3 via 2002:c058:6301::1 dev sit0 > /dev/null 2>&1                                                   
  ip -6 route del 2002:1101:101:0::/64 dev br0 > /dev/null 2>&1                                                              
  ip route flush dev sit0 > /dev/null 2>&1                                                                                   
  ip link set sit0 down > /dev/null 2>&1          
  echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
