#!/bin/sh

#wait to start web and run from goahead code
web_wait

LOG="echo ZEBRA: "

start() {
RIPEnable=`nvram_get 2860 RIPEnable`
if [ -f /bin/zebra ] && [ "$RIPEnable" = "1" ]; then
 if [ -f /etc/zebra.conf ]; then
    $LOG "Starting ZEBRA: "
    zebra -d -f /etc/zebra.conf
 fi
fi
}

stop() {
 $LOG "Stopping ZEBRA: "
  killall -q zebra
  killall -q -9 zebra
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
