#!/bin/sh

#get params
. /sbin/global.sh
. /sbin/config.sh

#wait to start web and run from goahead code
web_wait

LOG="echo RADVD: "

start() {
if [ -f /bin/radvd ] && [ "$CONFIG_IPV6" != "" ]; then
 if [ "$opmode" = "2" ]; then
    lan_if="eth2"
 fi
    radvd=`nvram_get 2860 radvdEnabled`
    ip -6 addr flush dev sit0
    ip -6 route flush dev sit0
    ip -6 link set sit0 down
    echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
    if [ "$radvd" = "1" ]; then
      $LOG "Starting radvd: "
        echo "1" > /proc/sys/net/ipv6/conf/all/forwarding
	$LOG "Up sit0 interface"
	ip -6 link set sit0 up

	$LOG "Add iptables rules fo ipv6"
	iptables -I INPUT  -p ipv6 -j ACCEPT
	iptables -I OUTPUT -p ipv6 -j ACCEPT
	iptables -I FORWARD  -p ipv6 -j ACCEPT
	ip6tables -A INPUT -j ACCEPT
	ip6tables -A FORWARD -j ACCEPT
	ip6tables -A OUTPUT -j ACCEPT
	ip6tables -F

	$LOG "Tunel ipv6 in ipv4 configure and up..."
	ipv6subnet="2000"
	relay6to4="192.88.99.1"
	ipv4=`ip route get $relay6to4 | awk {' print $5 '}`
	if [ "$ipv4" != "" ]; then
	    ipv6prefix=`echo $ipv4 | awk -F. '{ printf "2002:%02x%02x:%02x%02x", $1, $2, $3, $4 }'`
	    ip tunnel add tun6to4 mode sit ttl 64 remote any local $ipv4
	    ip link set dev tun6to4 up
	    ip -6 addr add ${ipv6prefix}::1/16 dev tun6to4
	    ip -6 route replace 2000::/3 via ::${relay6to4} dev tun6to4 metric 1
	    ip -6 addr add ${ipv6prefix}:${ipv6subnet}::1/64 dev $lan_if
	else
	    $LOG "No route to ip4v6 router..."
	fi
	$LOG "Configure radvd"
	echo > /etc/radvd.conf
	printf "
        interface $lan_if
	    {
    		AdvSendAdvert on;
    		MinRtrAdvInterval 30;
    		MaxRtrAdvInterval 100;
    		prefix 3ffe:501:ffff:100::/64
    		{
            		AdvOnLink on;
            		AdvAutonomous on;
            		AdvRouterAddr off;
    		};
	    };
	" > /etc/radvd.conf

	$LOG "Starting radvd"
	radvd -s -C /etc/radvd.conf -d 1 &

	$LOG "Send NS(change $lan_if state) to pass RFC4862"
	ip -6 addr del fe80::2e0:4cff:fe86:7001/64 dev $lan_if
	ip -6 addr add fe80::2e0:4cff:fe86:7001/64 dev $lan_if

	$LOG "Set alias IP for $lan_if to pass RFC1981 and RFC4443"
	ip -6 addr add 3ffe:501:ffff:100:2e0:4cff:fe86:7001/64 dev $lan_if:0
    fi
fi
}

stop() {
 $LOG  "Stop radvd daemon..."
if [ -f /bin/radvd ] && [ "$CONFIG_IPV6" != "" ]; then
  killall radvd > /dev/null 2>&1
  ip tunnel del tun6to4 > /dev/null 2>&1                                                                                                     
  ip link set dev tun6to4 down > /dev/null 2>&1
  ip -6 route flush dev sit0 > /dev/null 2>&1
  ip -6 addr flush dev sit0  > /dev/null 2>&1
  ip -6 link set sit0 down > /dev/null 2>&1
  echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
