#!/bin/sh

# if app not exist
if [ ! -f /bin/zebra ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

if [ "$opmode" = "0" ]; then
    exit 0
fi

LOG="logger -t zebra"

start() {
    RIPEnable=`nvram_get 2860 RIPEnable`
    if [ "$RIPEnable" = "1" ] && [ -f /etc/zebra.conf ]; then
	$LOG "Starting ZEBRA"
	zebra -d -f /etc/zebra.conf
    fi
}

stop() {
 $LOG "Stopping ZEBRA"
  killall -q zebra
  killall -q -SIGKILL zebra
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
