#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
    l2tp_pt=`nvram_get 2860 l2tpPassThru`
    ipsec_pt=`nvram_get 2860 ipsecPassThru`
    pptp_pt=`nvram_get 2860 pptpPassThru`

}

stop() {
 echo "Stopping vpnpass: "
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
