#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/wscd ]; then
 echo "Starting WPS: "
    wsc=`nvram_get 2860 WscModeOption`
    lan_ip=`nvram_get 2860 lan_ipaddr`
    opmode=`nvram_get 2860 OperationMode`
    if [ $wsc != "0" ]; then
	if [ $opmode = "0" ]; then
	    wscd -m 1 -a $lan_ip -i ra0 -D &
	else
	    wscd -m 1 -i ra0 -D &
	fi
    fi
fi
}

stop() {
 echo "Stopping WPS: "
    killall -q wscd
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
