#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t WSCD: "

start() {
if [ -f /bin/wscd ]; then
    get_param
    if [ "$wsc" = "1" ]; then
      $LOG "Starting WPS: "
	if [ "$opmode" = "0" ]; then
	    wscd -m 1 -a $lan_ip -i ra0 -D &
	else
	    wscd -m 1 -i ra0 -D &
	fi
    fi
fi
}

stop() {
 $LOG "Stopping WPS: "
    killall -q wscd
    killall -q -9 wscd
}

get_param() {
    wsc=`nvram_get 2860 WscModeOption`
    lan_ip=`nvram_get 2860 lan_ipaddr`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
