#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t dyndns"

start() {
if [ -f /bin/inadyn ]; then
    get_param
    if  [ "$ddns" != "" ] && [ "$srv" != "" ] && [ "$srv" != "none" ] && [ "$u" != "" ] && [ "$pw" != "" ]; then
	    $LOG "Starting DynDNS"
	if [ "$srv" = "dyndns.org" ]; then
	    inadyn -u $u -p $pw -a $ddns --dyndns_system dyndns@$srv --update_period_sec $update_period --background --syslog
	elif [ "$srv" = "freedns.afraid.org" ] || [ "$srv" = "zoneedit.com" ] || [ "$srv" = "no-ip.com" ]; then
	    inadyn -u $u -p $pw -a $ddns --dyndns_system default@$srv --update_period_sec $update_period --background --syslog
	else
	    $LOG "Unknown DDNS provider: $srv"
	    exit 1
	fi
    fi
fi
}

get_param() {
    srv=`nvram_get 2860 DDNSProvider`
    ddns=`nvram_get 2860 DDNS`
    u=`nvram_get 2860 DDNSAccount`
    pw=`nvram_get 2860 DDNSPassword`
    update_period="43200"
}

stop() {
 $LOG "Stopping DynDns"
    killall -q inadyn
    killall -q -9 inadyn
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
