#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t ntp"

start() {
    get_param

    $LOG "Set timezone"
    backup_time=`date +%T`

    if [ "$tz" = "" ]; then
        tz="MSD"
    fi

    echo $tz > /etc/tmpTZ
    sed -e 's#.*_\(-*\)0*\(.*\)#GMT-\1\2#' /etc/tmpTZ > /etc/tmpTZ2
    sed -e 's#\(.*\)--\(.*\)#\1\2#' /etc/tmpTZ2 > /etc/TZ
    rm -rf /etc/tmpTZ
    rm -rf /etc/tmpTZ2
    date +%T -s $backup_time

    if [ "$NTPEnabled" = "on" ] && [ "$srv" != "" ] && [ -f /bin/ntpd ]; then
	$LOG "Starting NTPD"
	ntpd -d -p $srv &
    fi
}

stop() {
 $LOG "Stopping NTPD"
    killall -q ntpd
    killall -q -9 ntpd
}

get_param() {
    NTPEnabled=`nvram_get 2860 NTPEnabled`
    srv=`nvram_get 2860 NTPServerIP`
    tz=`nvram_get 2860 TZ`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
