#!/bin/sh

# if app not exist
if [ ! -f /bin/igmpproxy ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

wait_connect

LOG="logger -t igmpproxy"

start() {
    #if igmpproxy enable and mode not full bridge
    get_param
    sysctl -w net.ipv4.igmp_max_memberships=5
    if [ "$igmpEnabled" = "1" ] && [ "$opmode" != "0" ]; then
        $LOG "Starting IGMPPROXY"
	wan_is_not_null=`ip -4 addr show $wan_if | grep inet -c`
	if [ "$wan_is_not_null" = "0" ]; then
    	    $LOG "Wait for adress get..."
	    sleep 20
	    killall -q igmpproxy
	    killall -q -SIGKILL igmpproxy
	fi
	printf "quickleave\nphyint $wan_if upstream  ratelimit 0  threshold 1\naltnet 0.0.0.0/0\nphyint $lan_if downstream  ratelimit 0  threshold 1\nphyint ppp0 disabled\n" > /etc/igmpproxy.conf
	echo 1 > "/proc/sys/net/ipv4/conf/$wan_if/forwarding"
	echo 1 > /proc/sys/net/ipv4/conf/all/mc_forwarding
	echo 1 > /proc/sys/net/ipv4/conf/default/mc_forwarding
	ip route replace 224.0.0.0/4 dev $wan_if
	if [ "$igmpSnoopMode" != "f" ] && [ "$igmpSnoopMode" != "n" ]; then
	    #if snoop mode unknown = auto
	    igmpSnoopMode=""
	fi
	if [ "$M2UEnabled" = "1" ]; then
	    #if wifi snoop enabled = force
	    igmpSnoopMode="f"
	fi
	if [ "$wan_port" = "4" ]; then
    	    igmpproxy -s$igmpSnoopMode /etc/igmpproxy.conf &
	else
    	    igmpproxy -sw$igmpSnoopMode /etc/igmpproxy.conf &
	fi
    else
	echo 0 > /proc/sys/net/ipv4/conf/all/mc_forwarding
	echo 0 > /proc/sys/net/ipv4/conf/default/mc_forwarding
    fi
}

stop() {
 $LOG "Stopping IGMPPROXY"
    killall -q igmpproxy
    killall -q -SIGKILL igmpproxy
    echo 0 > /proc/sys/net/ipv4/conf/all/mc_forwarding
    echo 0 > /proc/sys/net/ipv4/conf/default/mc_forwarding
    ip route del 224.0.0.0/4 dev $wan_if > /dev/null 2>&1
}

get_param() {
    igmpEnabled=`nvram_get 2860 igmpEnabled`
    igmpSnoopMode=`nvram_get 2860 igmpSnoopMode`
    M2UEnabled=`nvram_get 2860 M2UEnabled`
    wan_port=`nvram_get 2860 wan_port`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
