#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/udpxy ]; then
 UDPXY=`nvram_get 2860 UDPXYMode`
    if [ "$UDPXY" != "0" ] && [ "$UDPXY" != "" ]; then
        if [ "$wan_if" = "" ]; then                                                                                                         
            wan_igmp_if="eth2.2"                                                                                                            
        else                                                                                                                                
            wan_igmp_if=$wan_if                                                                                                             
        fi                         
        echo "UDPXY start"
	udpxy -m $wan_igmp_if -n-20 -c1 -H10 -R-1 -B64k -p81 -l /var/log/udpxy.log
    fi
fi
}

stop() {
    echo "UDPXY stop"
    killall -q udpxy
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
