#!/bin/sh

# if app not exist
if [ ! -f /bin/smbd ] || [ ! -f /bin/nmbd ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t samba"

start() {
SmbEnabled=`nvram_get 2860 SmbEnabled`
if [ "$SmbEnabled" = "1" ]; then
    get_param

    echo "[global]" > $CONFIG
    #for file share mode need increase buffers size
    echo "    interfaces = $interfaces" >> $CONFIG
    echo "    socket options = $socket_options" >> $CONFIG
    echo "    workgroup = $WorkGroup" >> $CONFIG
    echo "    netbios name = $SmbNetBIOS" >> $CONFIG
    echo "    server string = $SmbString" >> $CONFIG
    echo "    os level = $SmbOsLevel" >> $CONFIG
    echo "    force user = $Login" >> $CONFIG
    echo "    time server = $ntp_support" >> $CONFIG

    #add template to config
    cat /etc/smb.conf.template >> $CONFIG

    #share /media
    if [ -d /proc/bus/usb ]; then
	mounted=`df -h | grep "/dev/sd" | grep "media" -c`
	if [ $mounted != 0 ]; then
	    echo "[public]" >> $CONFIG
	    echo "    comment = pub" >> $CONFIG
	    echo "    path = /media" >> $CONFIG
	    echo "    public = yes" >> $CONFIG
	    echo "    browseable = yes" >> $CONFIG
	    echo "    guest ok = yes" >> $CONFIG
	    echo "    guest only = yes" >> $CONFIG
	    echo "    writable = yes" >> $CONFIG
	    echo "" >> $CONFIG
	fi
    fi

    if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
	$LOG "Already started... Stop WINS/SMB SERVER."
	killall -q smbd
	killall -q nmbd
	killall -q -SIGKILL smbd
	killall -q -SIGKILL nmbd
    fi
    $LOG "Starting WINS/SMB SERVER."
    find /var/log -type f -name "*mbd*" | while read samba_log; do
	echo > "$samba_log"
    done
    /bin/nmbd -s /etc/smb.conf -D &
    /bin/smbd -s /etc/smb.conf -D &
fi
}

stop() {
    if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
     $LOG "Stop WINS/SMB SERVER."
      killall -q nmbd > /dev/null
      killall -q smbd > /dev/null
      killall -q -SIGKILL nmbd > /dev/null
      killall -q -SIGKILL smbd > /dev/null
      rm -f /var/lock/*mbd.pid
    fi
}

get_param() {
    WorkGroup=`nvram_get 2860  WorkGroup`
    SmbNetBIOS=`nvram_get 2860 SmbNetBIOS`
    SmbString=`nvram_get 2860  SmbString`
    SmbOsLevel=`nvram_get 2860  SmbOsLevel`
    SmbTimeserver=`nvram_get 2860  SmbTimeserver`
    NTPEnabled=`nvram_get 2860 NTPEnabled`
    NTPServerIP=`nvram_get 2860 NTPServerIP`
    Login=`nvram_get 2860 Login`
    lan_ipaddr=`nvram_get 2860 lan_ipaddr`
    lan_netmask=`nvram_get 2860 lan_netmask`
    CONFIG="/etc/smb.conf"

    if [ "$SmbTimeserver" = "1" ] && [ "$NTPEnabled" = "on" ] && [ "$NTPServerIP" != "" ]; then
	ntp_support="yes"
    else
	ntp_support="no"
    fi
    if [ -d /proc/bus/usb ]; then
	socket_options="SO_BROADCAST IPTOS_THROUGHPUT TCP_NODELAY SO_RCVBUF=65536 SO_SNDBUF=65536" >> $CONFIG
    else
	socket_options="SO_BROADCAST IPTOS_THROUGHPUT TCP_NODELAY SO_RCVBUF=1024 SO_SNDBUF=1024" >> $CONFIG
    fi

    interfaces="lo 127.0.0.1/255.0.0.0 $lan_if $lan_ipaddr/$lan_netmask"
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
