#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

LOG="echo SAMBA: "

start() {
SmbEnabled=`nvram_get 2860 SmbEnabled`
if [ "$SmbEnabled" = "1" ]; then
    get_param

    echo "[global]" > $CONFIG
    echo "    socket options = SO_BROADCAST SO_RCVBUF=1024 SO_SNDBUF=1024" >> $CONFIG
    echo "    workgroup = $WorkGroup" >> $CONFIG
    echo "    netbios name = $SmbNetBIOS" >> $CONFIG
    echo "    server string = $SmbString" >> $CONFIG
    echo "    interfaces = $lan_if" >> $CONFIG
    echo "    force user = $Login" >> $CONFIG
    echo "    force group = Administrator" >> $CONFIG
    cat /etc/smb.conf.template >> $CONFIG

    if [ -f /bin/smbd ] && [ -f /bin/nmbd ]; then
	if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
	 $LOG "Already started... Stop WINS/SMB SERVER."
	    killall -q smbd
	    killall -q nmbd
	    sleep 1
	    killall -q -9 smbd
	    killall -q -9 nmbd
        fi
	$LOG "Starting WINS/SMB SERVER."
	echo > /var/log/samba.log
	echo > /var/log/nmbd.log
	rm -f /var/lock/*mbd.pid
	/bin/nmbd -s /etc/smb.conf -D &
	/bin/smbd -s /etc/smb.conf -D &
    fi
fi
}

stop() {
    if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
     $LOG "Stop WINS/SMB SERVER."
      killall -q nmbd > /dev/null
      killall -q smbd > /dev/null
      sleep 1
      killall -q -9 nmbd > /dev/null
      killall -q -9 smbd > /dev/null
      rm -f /var/lock/*mbd.pid
    fi
}

get_param() {
    WorkGroup=`nvram_get 2860  WorkGroup`
    SmbNetBIOS=`nvram_get 2860 SmbNetBIOS`
    SmbString=`nvram_get 2860  SmbString`
    Login=`nvram_get 2860 Login`
    CONFIG="/etc/smb.conf"
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
