#!/bin/sh

# if app not exist
if [ ! -f /bin/smbd ] || [ ! -f /bin/nmbd ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t samba"

start() {
SmbEnabled=`nvram_get 2860 SmbEnabled`
if [ "$SmbEnabled" = "1" ]; then
    get_param

    echo "[global]" > $CONFIG
    #for file share mode need increase buffers size
    if [ -d /proc/bus/usb ]; then
	echo "    socket options = SO_BROADCAST SO_RCVBUF=65536 SO_SNDBUF=65536" >> $CONFIG
    else
	echo "    socket options = SO_BROADCAST SO_RCVBUF=1024 SO_SNDBUF=1024" >> $CONFIG
    fi
    echo "    workgroup = $WorkGroup" >> $CONFIG
    echo "    netbios name = $SmbNetBIOS" >> $CONFIG
    echo "    server string = $SmbString" >> $CONFIG
    echo "    os level = $SmbOsLevel" >> $CONFIG
    echo "    interfaces = $lan_if" >> $CONFIG
    echo "    force user = $Login" >> $CONFIG
    echo "    coding system = utf8" >> $CONFIG
    echo "    character set = utf8" >> $CONFIG
    echo "    client code page = 866" >> $CONFIG
    cat /etc/smb.conf.template >> $CONFIG

    if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
	$LOG "Already started... Stop WINS/SMB SERVER."
	killall -q smbd
	killall -q nmbd
	killall -q -SIGKILL smbd
	killall -q -SIGKILL nmbd
    fi
    $LOG "Starting WINS/SMB SERVER."
    echo > /var/log/samba.log
    echo > /var/log/nmbd.log
    rm -f /var/lock/*mbd.pid
    /bin/nmbd -s /etc/smb.conf -D &
    /bin/smbd -s /etc/smb.conf -D &
fi
}

stop() {
    if [ -f /var/lock/smbd.pid ] || [ -f /var/lock/nmbd.pid ]; then
     $LOG "Stop WINS/SMB SERVER."
      killall -q nmbd > /dev/null
      killall -q smbd > /dev/null
      killall -q -SIGKILL nmbd > /dev/null
      killall -q -SIGKILL smbd > /dev/null
      rm -f /var/lock/*mbd.pid
    fi
}

get_param() {
    WorkGroup=`nvram_get 2860  WorkGroup`
    SmbNetBIOS=`nvram_get 2860 SmbNetBIOS`
    SmbString=`nvram_get 2860  SmbString`
    SmbOsLevel=`nvram_get 2860  SmbOsLevel`
    Login=`nvram_get 2860 Login`
    CONFIG="/etc/smb.conf"
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
