#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#include functions and env
. /etc/scripts/global.sh

LOG="logger -t shaper"

start() {
get_param
if [ -f /bin/tc ] && [ "$QoSEnable" != "" ] && [ "$QoSEnable" != "0" ]; then
 $LOG "Starting... "
    $LOG "Set default rules."
    set_def

    #chek wan is up
    wan_up=`ip link show $wan_if up | grep -c ""` > /dev/null 2>&1

    # increase queue length
    if [ "$wan_up" != "0" ]; then
	ifconfig $wan_if txqueuelen 1000
    fi
    ifconfig $lan_if txqueuelen 1000

    if [ "$QoSEnable" = "1" ]; then
	$LOG "Load netsched  modules."
	#netsched modules
	modprobe -q cls_u32
	modprobe -q cls_tcindex  
	modprobe -q cls_fw      
	modprobe -q act_gact  
	modprobe -q act_police  
	modprobe -q act_ipt
	modprobe -q em_cmp    
	modprobe -q em_u32    
	modprobe -q em_nbyte 
	modprobe -q sch_htb
	modprobe -q sch_dsmark
	#iptables modules
	modprobe -q xt_connmark
	modprobe -q xt_conntrack
	modprobe -q xt_dscp
	modprobe -q xt_mark
	modprobe -q xt_DSCP
	modprobe -q xt_MARK
	modprobe -q xt_DSCP
	modprobe -q xt_MARK
	modprobe -q ipt_TOS
	modprobe -q sch_sfq
	modprobe -q sch_red
	modprobe -q sch_gred
	$LOG " --------------RALINK-QOS------------------------"
	qos_run
    elif [ "$QoSEnable" = "2" ]; then
	    $LOG " --------------PRIO-QOS------------------------"
	    $LOG "Load netsched  modules."
	    modprobe -q sch_esfq
	    modprobe -q sch_sfq
	    modprobe -q cls_u32
	    modprobe -q em_u32    

	    #PRIOMAP+ESQ2LAN
	    tc qdisc add dev $lan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
	    tc qdisc add dev $lan_if parent 1:1 handle 10: esfq
	    tc qdisc add dev $lan_if parent 1:2 handle 20: esfq
	    tc qdisc add dev $lan_if parent 1:3 handle 30: esfq

	    #PRIOMAP+SFQ2WAN
	    if [ "$wan_up" != "0" ]; then
		tc qdisc add dev $wan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
		tc qdisc add dev $wan_if parent 1:1 handle 10: sfq
		tc qdisc add dev $wan_if parent 1:2 handle 20: sfq
		tc qdisc add dev $wan_if parent 1:3 handle 30: sfq
	    fi

	    #PORTS2PRIO
	    HIG_P="22 23 53 80 443 1720 5060"
	    MED_P="110 4190 1720 5190 5191 5192 5193 5222 5223 5269 5270 8080"
	    LOW_P="20 25 21 8010"

	    for port in $HIG_P
	    do
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:1
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:1
		if [ "$wan_up" != "0" ]; then
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:1
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:1
		fi
	    done

	    for port in $MED_P
	    do
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:2
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:2
		if [ "$wan_up" != "0" ]; then
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:2
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:2
		fi
	    done

	    for port in $LOW_P
	    do
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:3
		tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:3
		if [ "$wan_up" != "0" ]; then
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip sport $port 0xffff flowid 1:3
		    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport $port 0xffff flowid 1:3
		fi
	    done

	    #icmp
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip protocol 1 0xff flowid 1:1
	    if [ "$wan_up" != "0" ]; then
		tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip protocol 1 0xff flowid 1:1
	    fi
	    #udp
		tc filter add dev $lan_if parent 1:0 protocol ip prio 2 u32 match ip protocol 17 0xff flowid 1:2
	    if [ "$wan_up" != "0" ]; then
		tc filter add dev $wan_if parent 1:0 protocol ip prio 2 u32 match ip protocol 17 0xff flowid 1:2
	    fi
    elif [ "$QoSEnable" = "3" ]; then
	    $LOG " -----------------IMQ-FULL-------------------------"
	    $LOG "Load netsched  modules."
	    modprobe -q imq > /dev/null 2>&1
	    modprobe -q ipt_IMQ > /dev/null 2>&1
	    ip link set imq0 up > /dev/null 2>&1
	    ip link set imq1 up > /dev/null 2>&1
    fi
fi
}

stop() {
 $LOG "Stopping SHAPER"
 get_param
 set_def

    #drop others QoS rules
    INTERFACES=`ip link show up | grep -v lo | grep state | awk {' print $2 '} | grep -v "@" | cut -d ":" -f1` > /dev/null 2>&1
    for i in $INTERFACES; do
        echo $i;
	tc qdisc del dev $i root > /dev/null 2>&1
	tc qdisc del dev $i ingress > /dev/null 2>&1
    done
    if [ "$QoSEnable" = "1" ]; then
	qos_run c > /dev/null 2>&1
    fi
}

set_def() {
    tc qdisc del dev $wan_if root > /dev/null 2>&1
    tc qdisc del dev $wan_if ingress > /dev/null 2>&1
    tc qdisc del dev $lan_if root  > /dev/null 2>&1
    tc qdisc del dev $lan_if ingress > /dev/null 2>&1
    ip link set imq0 down > /dev/null 2>&1
    ip link set imq1 down > /dev/null 2>&1
}

get_param() {
    lan_ip=`nvram_get 2860 lan_ipaddr`
    nm=`nvram_get 2860 lan_netmask`
    QoSEnable=`nvram_get 2860 QoSEnable`

    #if ppp is up shaper to ppp0 else to wan_if
    if [ "$vpnEnabled" = "on" ]; then
        wan_if="ppp0"
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
