#!/bin/sh

# dns proxy
dnsp=`nvram_get 2860 dnsPEnabled`
admID=`nvram_get 2860 Login`

start() {
 echo "Starting DNSMASQ: "
 if [ -f /etc/dnsmasq.conf ]; then
    /sbin/dnsmasq --conf-file=/etc/dnsmasq.conf -u $admID -g $admID
 fi 
}

stop() {
 echo "Stopping DNSMASQ: "
  killall dnsmasq
 echo " Ok"
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
