#!/bin/sh

#get params
. /sbin/global.sh

lan_ip=`nvram_get 2860 lan_ipaddr`
nm=`nvram_get 2860 lan_netmask`

start() {
if [ -f /bin/igmpproxy ]; then
  echo "Starting IGMPPROXY: "
    igmp=`nvram_get 2860 igmpEnabled`
    if [ "$igmp" = "1" ]; then
	echo "quickleave" > /etc/igmpproxy.conf
	echo "phyint $wan_if upstream  ratelimit 0  threshold 1" >> /etc/igmpproxy.conf
	echo "altnet 0.0.0.0/0" >> /etc/igmpproxy.conf
	echo "phyint $lan_if downstream  ratelimit 0  threshold 1" >> /etc/igmpproxy.conf
	echo "phyint ppp0 disabled" >> /etc/igmpproxy.conf
	echo "" >> /etc/igmpproxy.conf
        igmpproxy $wan_if $lan_if /etc/igmpproxy.conf
    fi
fi
}

stop() {
 echo "Stopping IGMPPROXY: "
  killall igmpproxy > /dev/null 2>&1
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
