#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

start() {
if [ -f /bin/igmpproxy ]; then
    #workaround fix me later                                                                                                    
    killall -q -9 igmpproxy
    igmpen=`nvram_get 2860 igmpEnabled`
    if [ "$igmpen" = "1" ]; then
	echo "Starting IGMPPROXY: "
	printf "quickleave\nphyint $wan_if upstream  ratelimit 0  threshold 1\naltnet 0.0.0.0/0\nphyint $lan_if downstream  ratelimit 0  threshold 1\nphyint ppp0 disabled\n" > /etc/igmpproxy.conf
	sysctl -w net.ipv4.conf.all.mc_forwarding=1
	sysctl -w net.ipv4.conf.default.mc_forwarding=1
	route add -net 224.0.0.0/4 dev $wan_if  > /dev/null 2>&1
        igmpproxy /etc/igmpproxy.conf &
    else
	sysctl -w net.ipv4.conf.all.mc_forwarding=0
	sysctl -w net.ipv4.conf.default.mc_forwarding=0
    fi
fi
}

stop() {
 echo "Stopping IGMPPROXY: "
    killall -q igmpproxy
    route del -net 224.0.0.0/4 dev $wan_if  > /dev/null 2>&1
    sysctl -w net.ipv4.conf.all.mc_forwarding=0
    sysctl -w net.ipv4.conf.default.mc_forwarding=0
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
