#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait

lan_ip=`nvram_get 2860 lan_ipaddr`
nm=`nvram_get 2860 lan_netmask`

start() {
if [ -f /bin/igmpproxy ]; then
  echo "Starting IGMPPROXY: "
    igmp=`nvram_get 2860 igmpEnabled`
    #workaround fix me later                                                                                                    
    killall -q -9 igmpproxy
    if [ "$igmp" = "1" ]; then
	printf "
	    quickleave
	    phyint $wan_if upstream  ratelimit 0  threshold 1
	    altnet 0.0.0.0/0
	    phyint $lan_if downstream  ratelimit 0  threshold 1
	    phyint ppp0 disabled
	" >> /etc/igmpproxy.conf
        igmpproxy /etc/igmpproxy.conf &
    fi
fi
}

stop() {
 echo "Stopping IGMPPROXY: "
  killall -q igmpproxy
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
