#!/bin/sh

#get params
. /sbin/global.sh

start() {
 echo "Starting LLD2D: "
    lltd=`nvram_get 2860 lltdEnabled`
    if [ "$lltd" = "1" ]; then
        lld2d $lan_if
    fi
}

stop() {
 echo "Stopping LLD2D: "
  rm -rf /var/run/lld2d-*
  killall lld2d
 echo " Ok"
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
