#!/bin/sh

#get params
. /sbin/global.sh

start() {
if [ -f /bin/zebra ]; then
 if [ -f /etc/zebra.conf ]; then
    echo "Starting ZEBRA: "
    zebra -d -f /etc/zebra.conf
 fi
fi
}

stop() {
 echo "Stopping ZEBRA: "
  killall -q zebra
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
