#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

LOG="echo VPN: $1"

start() {
    vpnEnabled=`nvram_get 2860 vpnEnabled`
    if [ "$vpnEnabled" = "on" ]; then
     $LOG "Start vpnhelper"
      get_param
      #clear all configs and generate new
      echo > $ppp/chap-secrets
      echo > $ppp/pap-secrets
      echo > $ppp/connect-errors
      echo "$USER * $PASSWORD *" > $ppp/chap-secrets
      echo "$USER * $PASSWORD *" > $ppp/pap-secrets

      #call to vpn
      if [ "$vpnType" = "0" ]; then
	$LOG "PPPOE calling..."
	(sleep 5 && /etc/scripts/config-pppoe.sh) &
      elif [ "$vpnType" = "1" ]; then
	$LOG "PPTP calling..."
	(sleep 5 && /etc/scripts/config-pptp.sh) &
      elif [ "$vpnType" = "2" ]; then
	$LOG "L2TP calling..."
	(sleep 5 && /etc/scripts/config-l2tp.sh) &
      elif [ "$vpnType" = "6" ]; then
	$LOG "LANAUTH calling... $1"
	if [ "$1" ]; then
		/etc/scripts/config-lanauth.sh restart
	else
		(sleep 10 && /etc/scripts/config-lanauth.sh start) &
	fi
      fi
    fi
}

stop() {
 $LOG "Stop vpnhelper"
    killall -q config-pppoe.sh
    killall -q config-l2tp.sh
    killall -q config-pptp.sh
    killall -q -9 config-pppoe.sh
    killall -q -9 config-l2tp.sh
    killall -q -9 config-pptp.sh
    killall -q xl2tpd
    killall -q -9 xl2tpd
    killall -q pppd
    killall -q -9 pppd
    killall -q lanauth
    killall -q -9 lanauth
    rmmod ppp_mppe > /dev/null 2>&1
    rmmod pppol2tp > /dev/null 2>&1
    rmmod pptp     > /dev/null 2>&1
    rmmod ppp_generic     > /dev/null 2>&1

    #remove VPN server IP file
    rm -f /tmp/vpnip
}

get_param() {
      #get param
      vpnType=`nvram_get 2860 vpnType`
      USER=`nvram_get 2860 vpnUser`
      PASSWORD=`nvram_get 2860 vpnPassword`
      ppp=/etc/ppp
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start force
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
