#!/bin/sh

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

LOG="logger -t vpnhelper"

start() {
    if [ "$vpnEnabled" = "on" ]; then
      get_param

      #wait connetc to ap in sta mode
      #if VPN=PPPOE and vpnInterface=LAN no need wait
      if [ "$vpnType" != "0" ]; then
        wait_connect
      else
	if [ "$vpnInterface" != "LAN" ]; then
    	    wait_connect
	fi
      fi

      $LOG "Start vpnhelper"
      #clear all configs and generate new
      echo > $ppp/chap-secrets
      echo > $ppp/pap-secrets
      echo > $ppp/connect-errors
      echo "$vpnUser * $vpnPassword *" > $ppp/chap-secrets
      echo "$vpnUser * $vpnPassword *" > $ppp/pap-secrets

      #call to vpn
      if [ "$vpnType" = "0" ]; then
	$LOG "PPPOE calling..."
	(sleep 8 && /etc/scripts/config-pppoe.sh) &
      elif [ "$vpnType" = "1" ]; then
	$LOG "PPTP calling..."
	(sleep 8 && /etc/scripts/config-pptp.sh) &
      elif [ "$vpnType" = "2" ]; then
	$LOG "L2TP calling..."
	(sleep 8 && /etc/scripts/config-l2tp.sh) &
      elif [ "$vpnType" = "6" ]; then
	if [ "$lanauthpid" != "" ]; then
	    $LOG "LANAUTH call reload..."
	    /etc/scripts/config-lanauth.sh reload &
	else
	    $LOG "LANAUTH calling..."
	    (sleep 8 && /etc/scripts/config-lanauth.sh start) &
	fi
      fi
    fi
}

stop() {
 $LOG "Stop vpnhelper"
    #Kill helpers
    killall -q config-pppoe.sh
    killall -q config-l2tp.sh
    killall -q config-pptp.sh
    killall -q config-lanauth.sh
    killall -q -SIGKILL config-pppoe.sh
    killall -q -SIGKILL config-l2tp.sh
    killall -q -SIGKILL config-pptp.sh
    killall -q -SIGKILL config-lanauth.sh

    #send hup signal to pppd for correct link down
    killall -q -SIGHUP pppd
    sleep 1

    #Kill daemons
    killall -q xl2tpd
    killall -q -SIGKILL xl2tpd
    killall -q pppd
    killall -q -SIGKILL pppd

    #Kill lanauth only if vpn disable
    if [ "$vpnEnabled" = "off" ] || [ "$vpnType" != "6" ]; then
	    /etc/scripts/config-lanauth.sh stop
    fi

    #Remove modules
    mod="ppp_mppe blkcipher cryptomgr crypto_algapi pppol2tp pptp ppp_generic"
    for module in $mod
    do
	rmmod $module > /dev/null 2>&1
    done

    #Remove VPN server IP file
    rm -f /tmp/vpnip
}

get_param() {
    vpnInterface=`nvram_get 2860 vpnInterface`
    vpnUser=`nvram_get 2860 vpnUser`
    vpnPassword=`nvram_get 2860 vpnPassword`
    lanauthpid=`pidof lanauth`
    ppp=/etc/ppp
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
