#!/bin/sh

#get params
. /sbin/global.sh

start() {
 echo "Starting NTP: "
    srv=`nvram_get 2860 NTPServerIP`
    sync=`nvram_get 2860 NTPSync`
    tz=`nvram_get 2860 TZ`

    backup_time=`date +%T`
    sync=`expr $sync \* 3600`

    if [ "$tz" = "" ]; then
        tz="UCT_000"
    fi

    echo $tz > /etc/tmpTZ
    sed -e 's#.*_\(-*\)0*\(.*\)#GMT-\1\2#' /etc/tmpTZ > /etc/tmpTZ2
    sed -e 's#\(.*\)--\(.*\)#\1\2#' /etc/tmpTZ2 > /etc/TZ
    rm -rf /etc/tmpTZ
    rm -rf /etc/tmpTZ2
    date +%T -s $backup_time

    if [ "$srv" != "" ]; then
	ntpclient -s -c 0 -h $srv -i $sync &
    fi
}

stop() {
 echo "Stopping NTP: "
    killall ntpclient > /dev/null 2>&1
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
