#!/bin/sh

start() {
if [ -f /bin/udpxy ]; then
 QOS=`nvram_get 2860 WmmCapable`
    if [ "$QOS" = "1" ]; then
      echo "UDPXY start"
	udpxy -m br0 -n-20 -c1 -H10 -R-1 -B64k -p81 -l /var/log/udpxy.log
    fi
fi
}

stop() {
    echo "UDPXY stop"
    killall udpxy > /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
