#!/bin/sh

#get params
. /sbin/global.sh

lan_ip=`nvram_get 2860 lan_ipaddr`
nm=`nvram_get 2860 lan_netmask`
NAT=`nvram_get 2860 natEnabled`
SEC=`nvram_get 2860 SecurityMode`
IMQ=0
start() {
 echo "Starting SHAPER: "
    tc qdisc del dev $lan_if root > /dev/null 2>&1
    tc qdisc del dev $lan_if ingress > /dev/null 2>&1
    tc qdisc del dev $wan_if root  > /dev/null 2>&1
    tc qdisc del dev $wan_if ingress > /dev/null 2>&1
    if [ "$IMQ" = "1" ]; then
	echo "IMQ fullshape mode"
	ifconfig imq0 up
    else
	echo "Non IMQ base shaper mode"
	#output
	tc qdisc add dev $wan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
	tc qdisc add dev $wan_if parent 1:1 handle 10: sfq
	tc qdisc add dev $wan_if parent 1:2 handle 20: sfq
	tc qdisc add dev $wan_if parent 1:3 handle 30: sfq
	tc filter add dev $wan_if protocol ip parent 1: prio 1 u32 match ip dport 10000 0x3C00 flowid 1:1
	#input
	tc qdisc add dev $lan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
	tc qdisc add dev $lan_if parent 1:1 handle 10: sfq
	tc qdisc add dev $lan_if parent 1:2 handle 20: sfq
	tc qdisc add dev $lan_if parent 1:3 handle 30: sfq
	tc filter add dev $lan_if protocol ip parent 1: prio 1 u32 match ip dport 10000 0x3C00 flowid 1:1

    fi
	
}

stop() {
 echo "Stopping SHAPER: "
    tc qdisc del dev $lan_if root > /dev/null 2>&1
    tc qdisc del dev $lan_if ingress > /dev/null 2>&1
    tc qdisc del dev $wan_if root  > /dev/null 2>&1
    tc qdisc del dev $wan_if ingress > /dev/null 2>&1
    tc qdisc del dev imq0 root > /dev/null 2>&1
    tc qdisc del dev imq0 ingress > /dev/null 2>&1
    ifconfig imq0 down > /dev/null 2>&1
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
