#!/bin/sh

#get params
. /sbin/global.sh

#wait to start web and run from goahead code
web_wait


start() {
    vpnEnabled=`nvram_get 2860 vpnEnabled`
    if [ $vpnEnabled = "on" ]; then
     echo "Start vpnhelper"
      #get param
      vpnType=`nvram_get 2860 vpnType`
      USER=`nvram_get 2860 vpnUser`
      PASSWORD=`nvram_get 2860 vpnPassword`

      #clear all configs and generate new
      ppp=/etc/ppp                                                                                                                                
      echo > $ppp/chap-secrets                                                                                                                    
      echo > $ppp/pap-secrets                                                                                                                     
      echo > $ppp/connect-errors 
      echo "$USER * $PASSWORD *" > $ppp/chap-secrets
      echo "$USER * $PASSWORD *" > $ppp/pap-secrets

    
      #call to vpn
      if [ $vpnType = "0" ]; then
	echo "PPPOE calling..."
	(sleep 5 && /etc/scripts/config-pppoe.sh) &
      fi
      if [ $vpnType = "1" ]; then
	echo "PPTP calling..."
	(sleep 5 && /etc/scripts/config-pptp.sh) &
      fi
      if [ $vpnType = "2" ]; then
	echo "L2TP calling..."
	(sleep 5 && /etc/scripts/config-l2tp.sh) &
      fi
    fi
}

stop() {
 echo "Stop vpnhelper"
    killall -q config-pppoe.sh
    killall -q config-l2tp.sh
    killall -q config-pptp.sh
    killall -q -9 config-pppoe.sh
    killall -q -9 config-l2tp.sh
    killall -q -9 config-pptp.sh
    killall -q xl2tpd
    killall -q -9 xl2tpd
    killall -q pppd
    killall -q -9 pppd
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
