#!/bin/sh

start() {
 echo "Start goahead"
    killall -q nvram_daemon
    echo > /tmp/webrun
    /bin/goahead &
    sleep 10
}

stop() {
 echo "Stop goahead"
    killall -q -9 goahead
    killall -q -9 nvram_daemon
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
