#!/bin/sh

LOG="echo GOAHEADWEBSERVER: "

start() {
 $LOG "Start goahead"
    killall -q nvram_daemon
    $LOG "Copy web pages to tmpfs"
    mkdir -p /tmp/web
    cp -rpf /web/* /tmp/web
    $LOG "Run goahead"
    /bin/goahead &
    touch /tmp/webrun
    sleep 15
}

stop() {
 $LOG "Stop goahead"
    killall -q goahead
    killall -q nvram_daemon
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
