#!/bin/sh

LOG="echo GOAHEADWEBSERVER: "

start() {
 $LOG "Start goahead"
    fs backup_nvram
    fs save
    /bin/goahead &
    touch /tmp/webrun
    sleep 15
}

stop() {
 $LOG "Stop goahead"
    killall -q goahead
    killall -q -9 goahead
    killall -q nvram_daemon
    killall -q -9 nvram_daemon
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
