#!/bin/sh

#include functions and env
. /sbin/global.sh

start() {
if [ -f /bin/tc ]; then
 echo "Starting SHAPER: "
 get_param
    tc qdisc del dev $lan_if root > /dev/null 2>&1
    tc qdisc del dev $lan_if ingress > /dev/null 2>&1
    tc qdisc del dev $wan_if root  > /dev/null 2>&1
    tc qdisc del dev $wan_if ingress > /dev/null 2>&1
    if [ "$IMQ" = "1" ]; then
	echo "IMQ fullshape mode"
	ifconfig imq0 up
    else
	echo "Non IMQ base shaper mode"
	echo "------------------IN----------------------------"
	if [ "$LANUP" = "1" ]; then
	    #input
	    tc qdisc add dev $lan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
	    tc qdisc add dev $lan_if parent 1:1 handle 10: esfq
	    tc qdisc add dev $lan_if parent 1:2 handle 20: esfq
	    tc qdisc add dev $lan_if parent 1:3 handle 30: esfq

	    #HIGH icmp,ssh,https,telnet,sip,dns //fix me
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 21 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 22 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 23 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 53 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip dport 53 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 443 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip dport 443 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip sport 5060 0xffff flowid 1:1
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 1 u32 match ip protocol 1 0xff flowid 1:1

	    #MEDIUM http/ftpdata/udp
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 2 u32 match ip sport 80 0xffff flowid 1:2
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 2 u32 match ip dport 80 0xffff flowid 1:2
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 2 u32 match ip sport 20 0xffff flowid 1:2
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 2 u32 match ip protocol 17 0xff flowid 1:2

	    #LOW smtp/pop and others
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 3 u32 match ip sport 110 0xffff flowid 1:3
	    tc filter add dev $lan_if parent 1:0 protocol ip prio 3 u32 match ip sport 25 0xffff flowid 1:3
	fi
	echo "------------------OUT----------------------------"
	if [ "$WANUP" = "1" ]; then
	    #output
	    tc qdisc add dev $wan_if root handle 1: prio priomap 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0
	    tc qdisc add dev $wan_if parent 1:1 handle 10: sfq
    	    tc qdisc add dev $wan_if parent 1:2 handle 20: sfq
	    tc qdisc add dev $wan_if parent 1:3 handle 30: sfq
	    tc filter add dev $wan_if protocol ip parent 1: prio 1 u32 match ip dport 10000 0x3C00 flowid 1:1

	    #HIGH icmp,ssh,https,telnet,sip,dns //fix me
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 21 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 22 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 23 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 53 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip sport 53 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 443 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip sport 443 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip dport 5060 0xffff flowid 1:1
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 1 u32 match ip protocol 1 0xff flowid 1:1

	    #MEDIUM http/ftpdata/udp
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 2 u32 match ip dport 80 0xffff flowid 1:2
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 2 u32 match ip sport 80 0xffff flowid 1:2
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 2 u32 match ip dport 20 0xffff flowid 1:2
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 2 u32 match ip protocol 17 0xff flowid 1:2

	    #LOW smtp/pop and others
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 3 u32 match ip dport 110 0xffff flowid 1:3
	    tc filter add dev $wan_if parent 1:0 protocol ip prio 3 u32 match ip dport 25 0xffff flowid 1:3
	fi
    fi
fi
}

stop() {
 echo "Stopping SHAPER: "
 get_param
    for i in $INTERFACES; do
        echo $i;
	tc qdisc del dev $i root > /dev/null 2>&1
    done
    tc qdisc del dev $wan_if root > /dev/null 2>&1
    tc qdisc del dev $wan_if ingress > /dev/null 2>&1
    tc qdisc del dev $lan_if root  > /dev/null 2>&1
    tc qdisc del dev $lan_if ingress > /dev/null 2>&1
    ifconfig imq0 down > /dev/null 2>&1
    ifconfig imq1 down > /dev/null 2>&1

}

get_param() {
    lan_ip=`nvram_get 2860 lan_ipaddr`
    nm=`nvram_get 2860 lan_netmask`
    wan_mode=`nvram_get 2860 wanConnectionMode`
    NAT=`nvram_get 2860 natEnabled`
    SEC=`nvram_get 2860 SecurityMode`
    INTERFACES=`ip link show up | grep mtu | awk {' print $2 '} | grep -v "@" | cut -d ":" -f1`
    IMQ=0

    #if ppp is up shaper to ppp0 else to wan_if
    if [ "$wan_mode" = "PPPOE" -o  "$wan_mode" = "L2TP" -o "$wan_mode" = "PPTP"  ]; then
        wan_if="ppp0"
    else
	if [ "$wan_if" = "" ]; then
	    $wan_if="eth2.2"
	fi
    fi
    
    if [ "$lan_if" = "" ]; then
        lan_if="br0"
    else
        lan_if=$lan_if
    fi

    #check interfaces is up
    WANUP=`ip link show up | grep "$wan_if" -c`
    LANUP=`ip link show up | grep "$lan_if" -c`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
