#!/bin/sh

LOG="logger -t goahead"

start() {
 $LOG "Start goahead"
    #blink wps/sec led at boot time
    #before goahead start
    if [ -f /bin/gpio ]; then
	gpio l 13 0 4000 0 0 0
	gpio l 14 0 4000 0 0 0
    fi
    if [ -f /bin/goahead ]; then
	/bin/goahead &
    else
	echo "GOAHEAD NOT FOUND!!! FIX THIS AND REBUILD FIRMWARE."
    fi
}

stop() {
 $LOG "Stop goahead"
    killall -q goahead
    killall -q -SIGKILL goahead
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
