#!/bin/sh

LOG="logger -t goahead"

start() {
 $LOG "Start goahead"
    if [ -f /bin/goahead ]; then
	/bin/goahead &
    else
	echo "GOAHEAD NOT FOUND!!! FIX THIS AND REBUILD FIRMWARE."
    fi
}

stop() {
 $LOG "Stop goahead"
    killall -q goahead
    killall -q -9 goahead
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
