#!/bin/sh

LOG="logger -t GOAHEADWEBSERVER"

start() {
 $LOG "Start goahead"
    /bin/goahead &
}

stop() {
 $LOG "Stop goahead"
    killall -q goahead
    killall -q -9 goahead
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
