#!/bin/sh

start() {

 echo "Unload unneeded modules"
    rmmod -a

 echo "Drop caches"
    echo 1 /proc/sys/vm/drop_caches
    echo 2 /proc/sys/vm/drop_caches
    echo 3 /proc/sys/vm/drop_caches
    sync

 #if firts boot or restore
 if [ -f /var/MODIFIED ]; then
    echo "Save rwfs"
    fs save
 fi

}

stop() {
 echo "OK"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
