#!/bin/sh

LOG="echo MEMFREE: "

start() {

 $LOG "Unload unneeded modules"
    rmmod -a

 #if firts boot or restore
 if [ -f /var/MODIFIED ]; then
    ($LOG "Save rwfs" && sleep 20 && fs save) &
 fi

}

stop() {
 $LOG " "
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
