#!/bin/sh

#include functions from script
. /etc/scripts/functions

start() {
    
echo "Start NVRAM"
/bin/nvram_daemon &

echo "Init GPIO"
/bin/gpio r &

echo "Start goahead"
/bin/goahead &

echo "Start goahead DONE!!!"

}

stop() {
echo "Stop goahead"
    killall -9 goahead
    killall -9 nvram_daemon
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
