#!/bin/sh

#include functions from script
. /etc/scripts/functions

start() {
echo "Start goahead"
    goahead &
}

stop() {
echo "Stop goahead"
    killall -9 goahead
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
