#!/bin/sh

# Start all init scripts in /etc/rc.d
# executing them in numerical order.

TGZfs_size=131072
BLOCKS=2
MTDDEVICE=/dev/mtdblock5
ROOTDEVICE=/dev/mtdblock4

LOG="echo INIT"

#include profile variables
. /etc/profile

#mount tmpfs if present
tmpfs_av=`grep tmpfs -c < /proc/filesystems`
if [ "$tmpfs_av" != "0" ]; then
    #mount /tmp /etc in /var
    mkdir -p /var/tmpfs
    mount -o bind /var/tmpfs /tmp
    #make dir for rwfs and bind it
    mkdir -p /var/rwfs
    mount -o bind /var/rwfs /etc
    #need mount usbfs for usb support
    if [ -d /proc/bus/usb ]; then
	mount -t usbfs none /proc/bus/usb
    fi
fi

#autocreate some dev nodes
if [ -f /bin/mdev ]; then
    mdev -s
else
    mknod /dev/tty	c	5	0
    mknod /dev/ttyS0	c	4	64
    mknod /dev/ttyS1	c	4	65
    mknod /dev/ptmx		c	5	2
    for i in `seq 0 8`; do
	mknod /dev/mtdblock$i c 31 $i
    done
fi

$LOG "Create some folders in dev."
ndirs="/dev/pty /dev/tts /dev/cua /dev/misc"
for dir in $ndirs ; do
    mkdir -p "$dir" 2> /dev/null
done

$LOG "Create some persistent nodes in dev."
mknod /dev/tts/0	c	4	64
mknod /dev/tts/1	c	4	65
mknod /dev/cua/0	c	5	64
mknod /dev/misc/rtc	c	10	135

#ralink depended
mknod /dev/hwnat0	c	220	0
mknod /dev/swnat0	c	210	0
mknod /dev/rdm0	c	254	0
mknod /dev/PCM	c	233	0
mknod /dev/i2cM0	c	218	0
mknod /dev/I2S	c	234	0
mknod /dev/ac0	c	240	0
mknod /dev/acl0	c	230	0
mknod /dev/gpio	c	252	0
mknod /dev/pcm0	c	233	0
mknod /dev/i2s0	c	234	0
mknod /dev/cls0	c	235	0

for i in `seq 0 15`; do
    mknod /dev/pty/m$i c 2 $i
done

for i in `seq 0 3`; do
    mknod /dev/aci$i c 254 $i
done
for i in `seq 0 1`; do
    mknod /dev/gpio$i c 252 $i
done

$LOG "Mount /tmp/rootfs"
mkdir /tmp/rootfs
mount $ROOTDEVICE /tmp/rootfs -o ro

$LOG "Init DEV particion"
cp -rpf /tmp/rootfs/dev/* /dev

$LOG "Init RW particion"
bzcat $MTDDEVICE | /bin/tar xf - -C / > /dev/null 2>&1

if [ -f /etc/filesystem.ok ] && [ -f /etc/rc.d/rcS ]; then
    $LOG "RW File system is ok - preparing ..."
  else
    $LOG "File system is clear or poor."
    cp -af /tmp/rootfs/etc/* /etc
    $LOG "Restored. Save after full boot and configure."
    touch /etc/filesystem.ok
fi

$LOG "Umount /tmp/rootfs"
umount /tmp/rootfs
rm -rf /tmp/rootfs

if [ `cat /proc/meminfo | awk '/MemTotal:/ {print ($2>16384)}'` -eq 1 ]; then
#>16mb
    touch /tmp/is_32ram_dev
else
#<=16mb
    touch /tmp/is_16ram_dev
fi

$LOG "Start init now."
/bin/sh /etc/rc.d/rcS &
