#!/bin/sh

# if app not exist
if [ ! -f /bin/miniupnpd ]; then
    exit 0
fi

# wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t upnpd"

start() {
 get_param
    if [ "$upnpEnabled" = "1" -a "$real_wan_ipaddr" != "" ] && [ "$OperationMode" != "0" -o "$vpnEnabled" = "on" ]; then
	$LOG "Start upnp at $real_wan_ipaddr"
	if [ ! -f /var/upnp_leases ]; then
	    touch /var/upnp_leases
	fi
	gen_config
	ip route replace 239.0.0.0/8 dev $lan_if
        miniupnpd -f /etc/miniupnpd.conf -i "$real_wan_if" -o "$real_wan_ipaddr" -a "$lan_ipaddr/$lan_netmask" &
    fi
}

stop() {
 $LOG "Stop upnp "
    count=0
    while killall -q miniupnpd ; do
	if [ "$count" = "3" ]; then
	    killall -q -SIGKILL miniupnpd
	fi
	sleep 2
    done
    ip route del 239.0.0.0/8 dev "$lan_if" > /dev/null 2>&1
}

gen_config() {
####################generate config###########################
print "
minissdpdsocket=/var/run/minissdpd.sock
lease_file=/var/upnp_leases
enable_natpmp=yes
enable_upnp=yes
bitrate_up=3500000
bitrate_down=24000000
secure_mode=no
system_uptime=yes
notify_interval=60
clean_ruleset_threshold=20
clean_ruleset_interval=600
allow 1024-65535 $lan_ipaddr/$lan_netmask 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
model_number=1" > /etc/miniupnpd.conf
###############################################################
cat /etc/miniupnpd.conf.uuid >> /etc/miniupnpd.conf
###############################################################
}

get_param() {
    eval `nvram_buf_get 2860 lan_ipaddr lan_netmask upnpEnabled`
}


case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
