#!/bin/sh

# if app not exist
if [ ! -f /bin/radvd ] || [ ! -d /proc/sys/net/ipv6 ]; then
    exit 0
fi

#wait to start web and run from goahead code
. /etc/scripts/web_wait.sh
web_wait

#get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t radvd"

start() {
    radvdEnabled=`nvram_get 2860 radvdEnabled`
    if [ "$radvdEnabled" = "1" ] && [ "$IPv6_Enable" = "1" ]; then
	#
        # use old style tunnel mode
	use_sit=1;
        #
	if [ "$use_sit" = "1" ]; then
	    $LOG "Flush addres and route sit0 aninterface"
	    ip -6 addr flush dev sit0
	    ip -6 route flush dev sit0
	else
	    $LOG "Flush addres and route sit0 aninterface"
	    ip -6 addr flush dev tun6to4
	    ip -6 route flush dev tun6to4
	fi

	$LOG "Add iptables rules fo ipv6"
	iptables -I INPUT  -p ipv6 -j ACCEPT
	iptables -I OUTPUT -p ipv6 -j ACCEPT
	iptables -I FORWARD  -p ipv6 -j ACCEPT
	ip6tables -A INPUT -j ACCEPT
	ip6tables -A FORWARD -j ACCEPT
	ip6tables -A OUTPUT -j ACCEPT
	ip6tables -F

	$LOG "Tunel ipv6 in ipv4 configure and up..."
	if [ "$IPv6_6RD_Enable" = "1" ]; then
	    relay6to4="192.88.99.127"
	else
	    relay6to4="192.88.99.1"
	fi

	ipv6subnet="2000"
	if [ "$wan_ipaddr" != "" ]; then
	    ipv6prefix=`echo $wan_ipaddr | awk -F. '{ printf "2002:%02x%02x:%02x%02x", $1, $2, $3, $4 }'`
	    if [ "$use_sit" = "1" ]; then
		$LOG "Up sit0 interface"
		ip -6 link set sit0 up
		ip -6 addr add ${ipv6prefix}::1/16 dev sit0
		ip -6 route replace ${ipv6subnet}::/3 via ::${relay6to4} dev sit0 metric 1
	    else
		$LOG "Up tun6to4 interface"
		ip tunnel add tun6to4 mode sit ttl 64 remote any local $wan_ipaddr
		ip link set dev tun6to4 up
		ip -6 addr add ${ipv6prefix}::1/16 dev tun6to4
		ip -6 route replace ${ipv6subnet}::/3 via ::${relay6to4} dev tun6to4 metric 1
	    fi
	else
	    $LOG "No route to ip4v6 router..."
	fi

	$LOG "Configure radvd"
	echo > /etc/radvd.conf
	printf "
        interface $lan_if
	    {
    		AdvSendAdvert on;
    		MinRtrAdvInterval 30;
    		MaxRtrAdvInterval 100;
    		prefix ${ipv6prefix}:${ipv6subnet}::1/64
    		{
            		AdvOnLink on;
            		AdvAutonomous on;
            		AdvRouterAddr off;
    		};
	    };
	" > /etc/radvd.conf

	$LOG "Enable ipv6 route"
        echo "1" > /proc/sys/net/ipv6/conf/all/forwarding

	$LOG "Send NS(change $lan_if state) to pass RFC4862"
	ip -6 addr del fe80::2e0:4cff:fe86:7001/64 dev $lan_if			> /dev/null 2>&1
	ip -6 addr add fe80::2e0:4cff:fe86:7001/64 dev $lan_if

	$LOG "Set alias IP for $lan_if to pass RFC1981 and RFC4443"
	ip -6 addr del 3ffe:501:ffff:100:2e0:4cff:fe86:7001/64 dev $lan_if:0	> /dev/null 2>&1
	ip -6 addr add 3ffe:501:ffff:100:2e0:4cff:fe86:7001/64 dev $lan_if:0

	$LOG "Set ${ipv6prefix}:${ipv6subnet}::1/64 to $lan_if"
	ip -6 addr del ${ipv6prefix}:${ipv6subnet}::1/64 dev $lan_if		> /dev/null 2>&1
	ip -6 addr add ${ipv6prefix}:${ipv6subnet}::1/64 dev $lan_if

	$LOG "Starting radvd"
	radvd -s -C /etc/radvd.conf -d 1 &

    fi
}

stop() {
 $LOG  "Stop radvd daemon..."
    echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
    killall -q radvd
    killall -q -SIGKILL radvd
    ip -6 route flush dev tun6to4	> /dev/null 2>&1
    ip -6 addr flush dev tun6to4	> /dev/null 2>&1
    ip -6 route flush dev sit0		> /dev/null 2>&1
    ip -6 addr flush dev sit0		> /dev/null 2>&1
    ip link set dev tun6to4 down	> /dev/null 2>&1
    ip link set dev sit0 down		> /dev/null 2>&1
    ip tunnel del tun6to4		> /dev/null 2>&1
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
