#!/bin/sh

# Modified by N.Leiten and adopted for Wive-firmware, renamed in "fs"
# "flash" is a part of midge - mini distribuition for adm5120 based routers
# Copyright (C) 2004-2005 by Vladislav Moskovets <midge at vlad.org.ua>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU GPL v2 or later.

TGZfs_size=131072
BLOCKS=2
MTDDEVICE=/dev/mtdblock5


get_size(){
  ls -sk $1 |  sed -e "s/ \+/ /g" | cut -d" " -f2
}

usage(){
  echo "Usage: $0 | save | load | restore |" >&2
  exit 1
}

load(){
  local dst=/ 
  echo "Loading TGZfs"
  zcat $MTDDEVICE | tar xf - -C $dst>>/dev/null
}

save(){
  echo "Compress config files"
  tmp="/tmp/tgzfs"
  tar cf - /etc | gzip -9 > $tmp
  if [ "$(get_size $tmp)" -lt $(($TGZfs_size/1024)) ]; then
    echo "Write configs to flash"
    dd if=$tmp of=$MTDDEVICE bs=64k count=$BLOCKS conv=sync > /dev/null 2>&1
    echo "Config saved. OK."
  else
    echo "Error: File $tmp too big: $(get_size $tmp)k"
  fi
  rm $tmp
}

restore(){
  dd if=/dev/urandom of=$MTDDEVICE bs=64k count=$BLOCKS
  echo "123456789">$MTDDEVICE 
  echo "Restoring defaults..."
  reboot
}

main(){
  local cmd="$1"
  [ -z "$cmd" ] && usage
  shift
  case "$cmd" in 
    load) 
      load $@ 
      ;;
    save) 
      save $@ 
      ;;
    restore)
      restore $@
      ;;
    *) 
      usage $@ 
      ;;
  esac
}

main $@
