#!/bin/sh

INITDIR="/etc/init.d"
RC_DIR="/etc/rc.d"

if [ $# -eq 0 ]; then
   echo "Usage:"
   echo "      service <type> <args>"
   exit 1
fi

if [ "$1" = "list" ]; then
  ls $INITDIR/
  ls $RC_DIR/
  exit 1;
fi

if [ -x "$INITDIR/$1" ]; then
    ($RC_DIR/*"$1" "$2" 2>&1)
else
    echo "No such Service: $1 in $INITDIR";
    exit 1
fi

exit 0
