#!/bin/sh

INITDIR="/etc/init.d"
INITDIR2="/rwfs/init.d"

if [ $# -eq 0 ]; then
   echo "Usage:"
   echo "      service <type> <args>"
   exit 1
fi

if [ "$1" = "list" ]; then
  ls $INITDIR/
  ls $INITDIR2/
  exit 1;
fi

if [ -x $INITDIR/$1 ]; then
    $INITDIR/$1 $2
    else
    if [ -x $INITDIR2/$1 ]; then
        $INITDIR2/$1 $2
	else
        echo "No such Service: $1";
    fi
fi
