/* Autogenerated by script/mkversion.sh */
#define SAMBA_VERSION_MAJOR 3
#define SAMBA_VERSION_MINOR 3
#define SAMBA_VERSION_RELEASE 16
#define SAMBA_VERSION_OFFICIAL_STRING "3.3.16"
#define SAMBA_VERSION_STRING samba_version_string()
