#!/bin/sh

LOG="echo INETD: "

start() {
    get_param
    if [ -f /sbin/inetd ] && [ "$admID" != "" ]; then
      $LOG "Starting inetd: "
      echo > /etc/inetd.conf
	if [ -f /bin/dropbear ] && [ "$RemoteSSH" != "" ] && [ "$RemoteSSH" != "0" ]; then
	    echo "ssh     stream  tcp     nowait  $admID    /bin/dropbear       /bin/dropbear -i -K60 -I360 -m" >> /etc/inetd.conf
	fi
        /sbin/inetd
    fi
}

stop() {
 $LOG "Stopping inetd: "
 killall -q inetd
 killall -q -9 inetd
}

get_param() {
 admID=`nvram_get 2860 Login`
 RemoteSSH=`nvram_get 2860 RemoteSSH`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
