#!/bin/sh

#terminal settings
export TERM=xterm
export TERMCAP=/etc/termcap
export TERMINFO=/etc/xterm
export CONSOLE=/dev/console

#paths settings
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/etc/scripts
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/}
export TMPDIR=/tmp/
export TMP=/tmp/
export PS1='[`hostname`@`echo $PWD`]# '

#locale settings
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
export LC_NUMERIC=ru_RU.UTF-8
export LC_TIME=ru_RU.UTF-8
export LC_COLLATE=ru_RU.UTF-8
export LC_MONETARY=ru_RU.UTF-8
export LC_MESSAGES=ru_RU.UTF-8
export LC_PAPER=ru_RU.UTF-8
export LC_NAME=ru_RU.UTF-8
export LC_ADDRESS=ru_RU.UTF-8
export LC_TELEPHONE=ru_RU.UTF-8
export LC_MEASUREMENT=ru_RU.UTF-8
export LC_IDENTIFICATION=ru_RU.UTF-8
export LC_ALL=

#aliases
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi
