#!/bin/sh

#terminal settings
export TERM=xterm
export TERMCAP=/etc/termcap
export TERMINFO=/etc/xterm
export CONSOLE=/dev/console

#paths settings
if [ -d /opt/etc ]; then
    export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/etc/scripts:/opt/bin:/opt/sbin
else
    export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/etc/scripts
fi
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/}
export TMPDIR=/tmp/
export TMP=/tmp/
export PS1='[`hostname`@`echo $PWD`]# '

#locale settings
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
export LC_NUMERIC=ru_RU.UTF-8
export LC_TIME=ru_RU.UTF-8
export LC_COLLATE=ru_RU.UTF-8
export LC_MONETARY=ru_RU.UTF-8
export LC_MESSAGES=ru_RU.UTF-8
export LC_PAPER=ru_RU.UTF-8
export LC_NAME=ru_RU.UTF-8
export LC_ADDRESS=ru_RU.UTF-8
export LC_TELEPHONE=ru_RU.UTF-8
export LC_MEASUREMENT=ru_RU.UTF-8
export LC_IDENTIFICATION=ru_RU.UTF-8
export LC_ALL=

#variables for transmissions
if [ -f /bin/transmission-daemon ]; then
    torrent_home=`nvram_get 2860 torrent_home`
    if [ "$torrent_home" != "" ]; then
	export TRANSMISSION_HOME="$torrent_home"
	export TRANSMISSION_WEB_HOME=/share/transmission/web
	export XDG_DATA_HOME=/share/transmission/web
	export XDG_DATA_DIRS=/share/transmission/web
    fi
fi

#aliases
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi
