#!/bin/sh

#get params
. /etc/scripts/global.sh

#wait to start web and run from goahead code
web_wait

LOG="echo ChilliSpot: "
PARAMS="net dns1 dns2 domain radiuslisten radiusserver1 radiusserver2 \
    radiussecret radiusnasid radiusnasip radiuslocationid radiuslocationname \
    radiusnasporttype coaport lease uamserver uamhomepage uamsecret \
    uamallowed macallowed"
BOOLPARAMS="coanoipcheck uamanydns"

get_params() {
    PARLINE="--dhcpif br0"
    for i in $PARAMS; do
	val=`nvram_get 2860 chilli_$i`
	[ -n "$val" ] && PARLINE="$PARLINE --$i $val"
    done
    for i in $BOOLPARAMS; do
	val=`nvram_get 2860 chilli_$i`
	[ "$val" = "on" ] && PARLINE="$PARLINE --$i"
    done
}

start() {
if [ -f /bin/chilli ] && [ "$opmode" = "4" ]; then
 if [ -f /etc/chilli.conf ]; then
    $LOG "Starting ChilliSpot: "
    get_params
    modprobe tun
    chilli $PARLINE
 fi
fi
}

stop() {
 $LOG "Stopping ChilliSpot: "
  killall -q chilli
  killall -q -9 chilli
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
