/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_LIBGMP_FORCE
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_LIB_LIBNTFS3G_FORCE
#undef  CONFIG_LIB_ZLIB_FORCE
#undef  CONFIG_LIB_LIBSTDC_PLUS_FORCE
#undef  CONFIG_LIB_USB
#define CONFIG_LIB_NAT 1
#define CONFIG_LIB_FLEX 1

/*
 * Force build extra libraries in uClibc
 */
#define CONFIG_LIB_CRYPT_FORCE 1
#define CONFIG_LIB_LIBM_FORCE 1
#define CONFIG_LIB_NSL_FORCE 1
#define CONFIG_LIB_UTIL_FORCE 1
#define CONFIG_LIB_RESOLV_FORCE 1
#undef  CONFIG_LIB_RT_FORCE

/*
 * MTD utils
 */
#undef  CONFIG_USER_MTDUTILS
#undef  CONFIG_USER_MTDUTILS_ERASE
#undef  CONFIG_USER_MTDUTILS_ERASEALL
#undef  CONFIG_USER_MTDUTILS_FTL_CHECK
#undef  CONFIG_USER_MTDUTILS_FTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_MKFSJFFS
#undef  CONFIG_USER_MTDUTILS_MKFSJFFS2
#undef  CONFIG_USER_MTDUTILS_NFTLDUMP
#undef  CONFIG_USER_MTDUTILS_NFTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_NANDDUMP
#undef  CONFIG_USER_MTDUTILS_NANDTEST
#undef  CONFIG_USER_MTDUTILS_NANDWRITE
#undef  CONFIG_USER_MTDUTILS_DOC_LOADBIOS
#undef  CONFIG_USER_MTDUTILS_DOC_LOADIPL
#undef  CONFIG_LIB_ZLIB_FORCE

/*
 * Network Applications
 */
#undef  CONFIG_USER_BIGPOND
#undef  CONFIG_USER_CTORRENT
#undef  CONFIG_USER_DHCP6
#undef  CONFIG_USER_DHCP6_SERVER
#undef  CONFIG_USER_DHCP6_CLIENT
#define CONFIG_USER_DNSMASQ 1
#undef  CONFIG_USER_DISKTYPE
#undef  CONFIG_USER_ECHO_SERVER
#undef  CONFIG_USER_STORAGE
#undef  CONFIG_USER_STUPID_FTPD
#undef  CONFIG_USER_SAMBA
#define CONFIG_USER_GOAHEAD_HTTPD 1
#undef  CONFIG_USER_GOAHEAD_IPV6
#undef  CONFIG_USER_GOAHEAD_SSL
#define CONFIG_USER_GOAHEAD_HOSTNAME 1
#define CONFIG_USER_GOAHEAD_LANG_EN 1
#undef  CONFIG_USER_GOAHEAD_LANG_ZHTW
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_USER_MATRIXSSL
#define CONFIG_USER_IGMP_PROXY 1
#define CONFIG_USER_UDPXY 1
#define CONFIG_USER_WIVE 1
#undef  CONFIG_USER_KABINET
#define CONFIG_USER_INADYN 1
#define CONFIG_USER_IPTABLES_IPTABLES 1
#undef  CONFIG_USER_IPTABLES_SAVE_RESTORE
#undef  CONFIG_USER_IPTABLES_IP6TABLES
#define CONFIG_USER_TC 1
#undef  CONFIG_USER_MATRIXSSL
#define CONFIG_USER_MINIUPNPD 1
#define CONFIG_USER_WSC 1
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#undef  CONFIG_USER_MKDOSFS
#undef  CONFIG_USER_OPENSSL
#undef  CONFIG_USER_OPENSWAN
#undef  CONFIG_LIB_LIBGMP_FORCE
#define CONFIG_USER_DROPBEAR 1
#undef  CONFIG_USER_P910ND
#undef  CONFIG_USER_PORTMAP
#define CONFIG_USER_PPPD 1
#define CONFIG_USER_XL2TPD 1
#define CONFIG_USER_PPPPOE_RELAY 1
#define CONFIG_USER_ZEBRA 1
#define CONFIG_LIB_LIBZEBRA_FORCE 1
#undef  CONFIG_USER_RADVD
#undef  CONFIG_USER_RADVD_DUMP
#define CONFIG_USER_802_1X 1
#undef  CONFIG_USER_RT2561_802_1X
#undef  CONFIG_USER_TOTD
#undef  CONFIG_USER_WPA_SUPPLICANT
#undef  CONFIG_USER_OPENSSL

/*
 * Wireless-tools
 */
#define CONFIG_USER_WIRELESS_TOOLS 1
#define CONFIG_USER_WIRELESS_TOOLS_IWCONFIG 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWGETID
#undef  CONFIG_USER_WIRELESS_TOOLS_IWLIST
#define CONFIG_USER_WIRELESS_TOOLS_IWPRIV 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWSPY
#undef  CONFIG_USER_WIRELESS_TOOLS_IWEVENT

/*
 * Miscellaneous Applications
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#undef  CONFIG_USER_BONNIE
#define CONFIG_USER_ETHTOOL 1
#undef  CONFIG_USER_GDB_GDBREPLAY
#undef  CONFIG_USER_GDB_GDBSERVER
#undef  CONFIG_USER_NETCAT
#undef  CONFIG_USER_NETSTAT_NAT
#undef  CONFIG_USER_NTFS3G
#undef  CONFIG_USER_NTFSPROGS
#undef  CONFIG_LIB_LIBNTFS3G_FORCE
#undef  CONFIG_USER_STRACE_STRACE
#undef  CONFIG_USER_TCPDUMP
#undef  CONFIG_USER_PCIUTIL_LSPCI
#undef  CONFIG_USER_PCIUTIL_SETPCI

/*
 * Ralink RT288x Application
 */
#define CONFIG_RT2880_APP 1
#undef  CONFIG_RT2860V2_USER_MEMORY_OPTIMIZATION
#undef  CONFIG_RT2880_ATED
#undef  CONFIG_RT2880_REG_RW
#undef  CONFIG_RT2880_CSR_TEST
#undef  CONFIG_RT2880_FLASH_TEST
#undef  CONFIG_RT2880_HWNAT_TEST
#undef  CONFIG_RT2880_SWNAT_TEST
#define CONFIG_RT2880_MII_MGR 1
#define CONFIG_RT2880_NVRAM 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#define CONFIG_RT2880_RAINIT 1
#undef  CONFIG_RT2880_RADAEMON
#define CONFIG_RT2880_L2_MANAGE 1
#define CONFIG_RT2880_MTD 1
#undef  CONFIG_RT2880_GPIO_TEST
#undef  CONFIG_RT2880_SPI
#undef  CONFIG_RT2880_I2C
#undef  CONFIG_RALINKAPP_HWNAT
#define CONFIG_RALINKAPP_SWQOS 1
#define CONFIG_USER_IPROUTE2 1
#define CONFIG_USER_IPROUTE2_TC 1
#define CONFIG_RT3052_SWITCH 1
#undef  CONFIG_RALINKAPP_I2S
#undef  CONFIG_RALINKAPP_PCM
#undef  CONFIG_ASUS_NTFS3G

/*
 * Windows Rally Program
 */
#define CONFIG_USER_LLTD 1
#define CONFIG_VENDOR "Ralink"
#define CONFIG_PRODUCT "RT3052"
#define CONFIG_LINUXDIR "linux-2.6.21.x"
#define CONFIG_LIBCDIR ""
#define CONFIG_LANGUAGE ""
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
