/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_LIBGMP_FORCE
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#define CONFIG_LIB_LIBNVRAM_SSTRDUP 1
#define CONFIG_LIB_LIBNTFS3G_FORCE 1
#define CONFIG_LIB_ZLIB_FORCE 1
#undef  CONFIG_LIB_LIBSTDC_PLUS_FORCE
#define CONFIG_LIB_USB 1
#define CONFIG_LIB_NAT 1
#define CONFIG_LIB_FLEX 1
#define CONFIG_LIB_EVENT 1
#define CONFIG_LIB_CURL 1
#undef  CONFIG_LIB_PCAP
#define CONFIG_LIB_ICONV 1
#undef  CONFIG_LIB_NET
#define CONFIG_LIB_NFNETLINK 1
#undef  CONFIG_LIB_UPNP

/*
 * Force build extra libraries in uClibc
 */
#define CONFIG_LIB_CRYPT_FORCE 1
#define CONFIG_LIB_LIBM_FORCE 1
#define CONFIG_LIB_NSL_FORCE 1
#define CONFIG_LIB_UTIL_FORCE 1
#define CONFIG_LIB_RESOLV_FORCE 1

/*
 * Network Applications
 */
#define CONFIG_USER_GOAHEAD_HTTPD 1
#undef  CONFIG_USER_GOAHEAD_IPV6
#undef  CONFIG_USER_GOAHEAD_SSL
#define CONFIG_USER_GOAHEAD_HOSTNAME 1
#define CONFIG_USER_GOAHEAD_HAS_WPSBTN 1
#define CONFIG_USER_GOAHEAD_LANG_EN 1
#undef  CONFIG_USER_GOAHEAD_LANG_ZHTW
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_USER_MATRIXSSL
#undef  CONFIG_USER_DHCP6
#undef  CONFIG_USER_DHCP6_SERVER
#undef  CONFIG_USER_DHCP6_CLIENT
#define CONFIG_USER_DNSMASQ 1
#undef  CONFIG_USER_SAMBA
#define CONFIG_USER_SAMBA3 1
#define CONFIG_LIB_ICONV 1
#define CONFIG_USER_TRANSMISSION 1
#define CONFIG_LIB_EVENT 1
#define CONFIG_LIB_CURL 1
#define CONFIG_LIB_ZLIB_FORCE 1
#define CONFIG_USER_OPENSSL 1
#define CONFIG_USER_STORAGE 1
#define CONFIG_USER_IGMP_PROXY 1
#define CONFIG_USER_UDPXY 1
#define CONFIG_USER_WIVE 1
#define CONFIG_USER_KABINET 1
#define CONFIG_USER_INADYN 1
#define CONFIG_USER_IPTABLES_IPTABLES 1
#undef  CONFIG_USER_IPTABLES_SAVE_RESTORE
#define CONFIG_USER_IPTABLES_IP6TABLES 1
#define CONFIG_USER_TC 1
#define CONFIG_USER_DROPBEAR 1
#define CONFIG_USER_P910ND 1
#undef  CONFIG_USER_PORTMAP
#define CONFIG_USER_PPPD 1
#define CONFIG_USER_PPPD_CHAT 1
#define CONFIG_USER_XL2TPD 1
#undef  CONFIG_USER_PPPPOE_RELAY
#define CONFIG_USER_PARPROUTED 1
#undef  CONFIG_USER_ZEBRA
#define CONFIG_USER_SNMPD 1
#define CONFIG_USER_MINIUPNPD 1
#define CONFIG_USER_XUPNPD 1
#define CONFIG_USER_RADVD 1
#define CONFIG_USER_CDP 1
#define CONFIG_USER_LLTD 1
#undef  CONFIG_USER_802_1X
#undef  CONFIG_USER_WSC
#define CONFIG_LIB_NFNETLINK 1
#define CONFIG_USER_OPENSSL 1
#undef  CONFIG_USER_OPENSWAN
#undef  CONFIG_LIB_LIBGMP_FORCE
#undef  CONFIG_USER_WPA_SUPPLICANT

/*
 * Wireless-tools
 */
#define CONFIG_USER_WIRELESS_TOOLS 1

/*
 * Miscellaneous Applications
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#undef  CONFIG_USER_BONNIE
#undef  CONFIG_USER_ETHTOOL
#undef  CONFIG_USER_GDB_GDBREPLAY
#undef  CONFIG_USER_GDB_GDBSERVER
#undef  CONFIG_USER_NETSTAT_NAT
#define CONFIG_USER_NTFS3G 1
#undef  CONFIG_USER_NTFSPROGS
#define CONFIG_LIB_LIBNTFS3G_FORCE 1
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#undef  CONFIG_USER_STRACE_STRACE
#undef  CONFIG_USER_TCPDUMP
#undef  CONFIG_USER_CHILLISPOT
#undef  CONFIG_USER_PCIUTIL_LSPCI
#undef  CONFIG_USER_PCIUTIL_SETPCI

/*
 * Ralink RT288x Application
 */
#define CONFIG_RT2880_APP 1
#undef  CONFIG_RT2860V2_USER_MEMORY_OPTIMIZATION
#undef  CONFIG_RT2880_ATED
#undef  CONFIG_RT2880_REG_RW
#undef  CONFIG_RT2880_CSR_TEST
#define CONFIG_RT2880_FLASH_TEST 1
#define CONFIG_RT2880_MII_MGR 1
#define CONFIG_RT2880_NVRAM 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#define CONFIG_RT2880_RAINIT 1
#undef  CONFIG_RT2880_RADAEMON
#define CONFIG_RT2880_L2_MANAGE 1
#define CONFIG_RT2880_MTD 1
#undef  CONFIG_RT2880_MTD_VERF
#define CONFIG_RT2880_GPIO_TEST 1
#undef  CONFIG_RT2880_SPI
#undef  CONFIG_RT2880_I2C
#define CONFIG_RALINKAPP_HWNAT 1
#undef  CONFIG_RALINKAPP_HWNAT_AC
#undef  CONFIG_RALINKAPP_HWNAT_ACL
#undef  CONFIG_RALINKAPP_HWNAT_MTR
#define CONFIG_RALINKAPP_SWQOS 1
#undef  CONFIG_RALINKAPP_CLS
#define CONFIG_USER_IPROUTE2 1
#define CONFIG_USER_IPROUTE2_TC 1
#undef  CONFIG_RT3052_SWITCH
#define CONFIG_RTL8367M_SWITCH 1
#undef  CONFIG_RALINKAPP_I2S
#undef  CONFIG_RALINKAPP_PCM

/*
 * 3G support
 */
#define CONFIG_USB_MODESWITCH 1
#define CONFIG_LIB_USB 1

/*
 * Optimization options.
 */
#undef  CONFIG_LIB_SMALLSIZE
#undef  CONFIG_USER_SMALLSIZE
#define CONFIG_VENDOR "Ralink"
#define CONFIG_PRODUCT "RT3052"
#define CONFIG_LINUXDIR "linux"
#define CONFIG_LIBCDIR ""
#define CONFIG_LANGUAGE ""
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
