#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/Wive-RTNL/toolchain/bin/mipsel-linux-uclibc-gcc  -DOPENSSL_THREADS  -Os -DL_ENDIAN -mips32r2 -mno-branch-likely -G 0 -fno-builtin -DCPU=MIPS32 -DMIPSEL -DNO_STRINGS_H -fPIC"
  #define PLATFORM "RT2880"
  #define DATE "Tue Aug  9 03:18:31 OMSST 2011"
#endif
