#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/Wive-RTNL/toolchain/bin/mipsel-linux-uclibc-gcc -Os"
  #define PLATFORM "RT2880"
  #define DATE "Tue Apr  5 02:55:08 OMSST 2011"
#endif
