diff --git a/user/Makefile b/user/Makefile
index eae512e..8fee9d8 100644
--- a/user/Makefile
+++ b/user/Makefile
@@ -41,8 +41,8 @@ dir_$(CONFIG_USER_GDBSERVER_GDBSERVER)      += gdbserver
 dir_$(CONFIG_USER_STRACE_STRACE)            += strace
 dir_$(CONFIG_USER_WIRELESS_TOOLS)           += wireless_tools
 dir_$(CONFIG_USER_WIRELESS_IW_TOOL)         += iw
-#dir_$(CONFIG_USER_IPTABLES_IPTABLES)        += iptables
-#dir_$(CONFIG_USER_IPTABLES_IP6TABLES)       += iptables
+dir_$(CONFIG_USER_IPTABLES_IPTABLES)        += iptables
+dir_$(CONFIG_USER_IPTABLES_IP6TABLES)       += iptables
 dir_$(CONFIG_USER_CDP)			    += cdp-tools
 dir_$(CONFIG_USER_LLTD)			    += lldt
 dir_$(CONFIG_USER_INADYN)                   += inadyn
@@ -59,7 +59,7 @@ dir_$(CONFIG_USER_ETHTOOL)                  += ethtool
 dir_$(CONFIG_USER_UDPXY)                    += udpxy
 dir_$(CONFIG_USER_WIVE)			    += wive-utils
 dir_$(CONFIG_USER_KABINET)		    += kabinet
-#dir_$(CONFIG_USER_MINIUPNPD)                += miniupnp
+dir_$(CONFIG_USER_MINIUPNPD)                += miniupnp
 dir_$(CONFIG_USER_XUPNPD)		    += xupnpd
 dir_$(CONFIG_USER_RADVD)               	    += radvd
 dir_$(CONFIG_USER_ZEBRA)		    += quagga
diff --git a/user/miniupnp/Makefile b/user/miniupnp/Makefile
index ccbda22..dd7e00d 100644
--- a/user/miniupnp/Makefile
+++ b/user/miniupnp/Makefile
@@ -136,9 +136,10 @@ endif # ($(TEST), 1)
 endif # ifdef IPTABLESPATH
 endif # ifdef PCFILE_FOUND
 
-LIBS += $(IPTABLESPATH)/libiptc/libiptc.a $(ROOTDIR)/lib/lib/libnfnetlink.so
+CFLAGS := $(CFLAGS) -DIPTABLES_143
+LIBS += $(IPTABLESPATH)/filesystem/lib/libxtables.a
 
-TEST := $(shell pkg-config --atleast-version=1.0.2 libnetfilter_conntrack && pkg-config --atleast-version=1.0.3 libmnl && echo 1)
+TEST :=
 ifeq ($(TEST),1)
 CFLAGS += -DUSE_NFCT
 LIBS += $(shell pkg-config --static --libs-only-l libmnl)
diff --git a/user/radvd/DoConfigure.sh b/user/radvd/DoConfigure.sh
index eaff1ec..ff1406d 100755
--- a/user/radvd/DoConfigure.sh
+++ b/user/radvd/DoConfigure.sh
@@ -19,6 +19,4 @@ HTARGET=mipsel-linux
 CONFOPTS="--host=$HTARGET --target=$HTARGET --build=$HBUILD"
 CONFOPTS="$CONFOPTS --prefix=$APROOTDIR/filesystem --disable-dependency-tracking"
 
-export LDFLAGS=-L../../lib/libflex
-
 ./configure $CONFOPTS
